# Question bank, mixed set. Deliberately disjoint from week-2, week-3 and week-4:
# cross-week comparisons, and the details those three sets leave out. Nothing here
# repeats or rephrases a question she has already answered.

MIXED = [
('The Greeks &middot; before Plato',
 'Homer wrote in the eighth century BCE. What picture of the world does the <i>Odyssey</i> rely on?',
 [('A cosmos with an order and a place for everything in it.',
   'Eighth century BCE. It supplies the one thing nobody in the course disputes: there is an order out there. Every later argument is about where that order is and how a person gets at it. Heraclitus then says nature is in harmony, Plato puts the order in a realm outside ours, and Aristotle puts it in the things themselves.'),
  ('A world of pure chance, where the gods intervene at random.',
   'The opposite of the picture she drew from it.'),
  ('An early form of the scientific method.',
   'Nothing in the lecture claims that.'),
  ('A separation between nature and the work of people.',
   "That split is Schadewaldt's subject, and he says the Greeks did <b>not</b> have it.")],
 1, 'He is in the course to supply the assumption the Greeks all share before anyone starts arguing.'),

('Plato &middot; what happens to the man who goes back',
 'In the cave, a prisoner gets free, goes up, sees the sun, and comes back down. What do the others do?',
 [('They follow him out.',
   'If leaving were that easy there would be no allegory.'),
  ('They laugh at him, and they would kill anyone who tried to free them.',
   'Two separate reactions and they are easy to run together. Ridicule is for the returner. The killing is reserved for whoever tries to unchain them. Plato is writing not long after Athens executed Socrates, which is the obvious thing the second half is pointing at.'),
  ('They kill him on sight.',
   'The common misremembering. The ridicule falls on the returner; the threat of killing attaches to the act of unchaining.'),
  ('They ignore him and carry on watching the wall.',
   'Too mild for the text, which gives them both a reaction and a threat.')],
 2, 'Two different reactions, aimed at two different things he might do.'),

('Plato against Bacon &middot; what mathematics is for',
 'Both Plato and the new science of the 1600s put mathematics near the centre. They want different things from it. What is the difference?',
 [('Plato uses it to predict what bodies will do; the new science uses it to train the mind.',
   'The right contrast with the two sides swapped.'),
  ('For Plato it gives access to the abstract, to what you cannot touch; for the new science it is a law like gravity, used to predict where the planets will be.',
   'Which is why Plato wants his philosopher kings taught geometry and astronomy: the subjects deal in things you cannot touch, so they turn the soul away from the visible world. The new science wants the opposite, a number you can check against the sky tomorrow night.'),
  ('Plato rejected mathematics as a distraction from dialectic.',
   'He requires it in the education of his rulers.'),
  ('Both use it the same way, so there is no contrast to draw.',
   'She drew one explicitly, in the Bacon lecture.')],
 2, "One of them wants mathematics to point away from the visible world. The other wants it to point at tomorrow night's sky."),

('Schadewaldt &middot; whose dualism',
 'Schadewaldt says modern thought developed a dualism between thought and extension. Which philosopher is that split usually credited to?',
 [('Aristotle.',
   'His form and matter sit together in one object, so no such split.'),
  ('Descartes.',
   'Thinking substance against extended substance: mind on one side, everything that takes up space on the other. Once the observer is made of one kind of thing and the world of another, the observer is standing outside what is observed, which is the arrangement Schadewaldt wants undone.'),
  ('Hume.',
   'Not a figure in these lectures.'),
  ('Bacon.',
   "Bacon's split is between the knower and nature as something to be forced to answer, and the thought-and-extension formula is not his.")],
 2, 'Thinking substance on one side, and everything that takes up space on the other.'),

('Comte &middot; the three states',
 'Auguste Comte claims explanation passes through three historical stages. One explains events by the will of gods. One explains them by abstract forces and essences. One admits only what can be observed and measured. In what order do they come, and what is the third called?',
 [('Gods, then abstract forces, then the observable. The third is the positive stage.',
   'The word positivism comes from that third stage, which is the reason he is in this material at all. Note the shape of the claim: each stage improves on the last, so Comte is telling a progress story, which puts him on the opposite side from Kuhn.'),
  ('The observable, then abstract forces, then gods. The third is the theological stage.',
   'This runs the sequence backwards, and it would make religion the most advanced form of explanation.'),
  ('Abstract forces, then gods, then the observable. The third is the empirical stage.',
   'The order is wrong in the middle, and empirical is not his name for it.'),
  ('Gods, then the observable, then abstract forces. The third is the metaphysical stage.',
   'The first is right and the other two are swapped, which would have explanation moving away from measurement at the end.')],
 1, 'The third stage shares its name with a doctrine Kuhn later attacks.'),

('The Vienna Circle',
 'What was the Vienna Circle?',
 [('A group of 1920s and 1930s philosophers and scientists who held that a statement means something only if it can be checked against experience.',
   "Logical positivism, with Moritz Schlick at the centre. It is the hardest and most organised version of the doctrine Kuhn's book breaks with, which is why she introduced Kuhn as marking a break with positive doctrines."),
  ('A circle of Renaissance astronomers around Copernicus.',
   'Four centuries too early and the wrong city.'),
  ('The group of feminist philosophers of science from week 5.',
   'Different century, different argument.'),
  ("Foucault's circle of French historians.",
   'Not a group in this course.')],
 1, 'Their test for whether a sentence means anything is the same test positivism applies to knowledge.'),

('Bacon against Aristotle &middot; what the patient method produced',
 'Bacon objects that the Aristotelian waits for the world to reveal its built-in purposes. Two thousand years of that patience produced geocentrism, the earth at the centre with everything turning round it. Why does that damage the method, beyond showing it to be slow?',
 [('Geocentrism is no part of the right answer, so the patient method did not hand over an incomplete truth.',
   "It handed over a different system, and gave no sign of having gone wrong. The force of it is what the waiting produced. If the world reveals itself to whoever waits, then waiting should give you a piece of the answer, incomplete and pointing the right way. Geocentrism points nowhere near. And it is no accident the method failed to catch: <b>the <i>telos</i> doctrine generated it.</b> Earth's natural place is the centre, which is why a dropped rock falls, and by the same reasoning the earth sits at the centre of everything. So asking what things are for, and following the answer through, produced a confident and detailed account that was wrong in every part that mattered, with nothing in the method to flag it. Galileo, 1564 to 1642, pointed an instrument at the sky and found otherwise. And it is why Bacon wants experiment: watching the sky patiently gives you a sun that moves."),
  ('It shows the method is slow, so a faster one was needed.',
   'Speed is the objection the question sets aside, and a slow method that arrives is still a method that works.'),
  ('It shows the senses are unreliable, because they reported the wrong thing.',
   'Tempting, and the senses reported correctly. The sun really does appear to cross the sky, and a rock really does fall. What went wrong is the step from how things appear to what is the case.'),
  ('It shows Aristotle had too little data, so more observing would have corrected it.',
   'The reverse. More observation of the same kind confirms geocentrism every single day, which is exactly what made the error so stable.')],
 1, 'The stem rules out slowness. Ask what the method handed over after all that time, and whether it was even a piece of the right answer.'),

('Lynn White &middot; from a belief about time to a watermill',
 'Lynn White argues that the Judaeo-Christian worldview is why Western Europe built the technology it built. One step in his reasoning is that Christian history runs in one direction toward an end point, where most religions had time going round in a circle. How does that step get him from a belief about time to more machinery?',
 [('A history with an end point means there is no time to lose, so work becomes urgent, and manual work turns into a pressing form of worship.',
   'That is the hinge of the whole argument. In a world that goes round in a circle, hurrying gains you nothing, because everything returns to where it started. Give history a destination and every hour spent is an hour nearer or further from it. Labour stops being a burden and becomes something owed. Once building a better mill counts as devotion, mills get built.'),
  ('A history with an end point means the world is about to be destroyed, so people built machines to protect themselves.',
   'Fear of an ending is not the mechanism. The end point in his account is a goal to be reached, and it makes work valuable.'),
  ('A one-directional history makes the past useless, so every generation had to invent its tools over again.',
   'That would slow technology down, and his argument is about what sped it up.'),
  ('It does not get him anywhere. The step is decorative, and the real driver in his account is economic need.',
   'Economic need driving technology, with religion trailing behind, is the position his argument is written against.')],
 1, 'Compare it with a history that goes round in a circle and returns to its start. What changes about the value of hurrying?'),

('Across weeks &middot; the same three words, twice',
 'Bacon writes that knowledge is power. Foucault writes power-knowledge. One claim is in both: that knowing a thing and having power over it are a single act. What are the two differences between them?',
 [("Bacon's power is over the physical world, and he presents it as a good thing.",
   "Foucault's power is over people, and he presents it as a danger. Bacon is selling the idea: learn how nature works and you can build engines and stop epidemics. Foucault is warning against it: the file a prison writes about a man becomes the truth about him and decides whether he goes home. Same equation, and the thing under the power has changed from nature to people, and the writer has gone from recommending it to warning about it. Her notes say Foucault builds on Bacon, so the echo is deliberate."),
  ('Bacon means it literally and Foucault means it as a figure of speech.',
   'Foucault means it as literally as Bacon does. A written record about a person really does determine what happens to that person.'),
  ('Bacon is describing the future and Foucault is describing the past, so the two never disagree.',
   'Both are describing how knowing works in general, and they disagree sharply about whether it is something to welcome.'),
  ('There is no connection between them. The resemblance in wording is a coincidence.',
   "Her notes say directly that Foucault builds on Bacon's knowledge is power.")],
 1, 'One difference is about what or who the power is exercised over. The other is about whether the writer thinks it is a good thing.'),

('Across weeks &middot; two perfectly ordered cities',
 'Plato describes the Kalliopolis. Foucault describes the plague town and the panoptic utopia. Both are cities where order reaches into everything. What separates them?',
 [("Plato's is imaginary and Foucault's is historical, so they have nothing in common.",
   'The plague town is historical and the panopticon was never built, so the line does not fall there. And she put the two side by side on purpose.'),
  ('The arrangement is close to the same. Plato presents it as the best possible city, and Foucault presents it as what modern institutions actually do to people.',
   "She wrote on her own slide, beside the panoptic utopia, think Plato, <i>Republic</i>, the Kalliopolis. The same dream described twice, once as an ideal and once as a diagnosis. Which means Foucault's target is older than the nineteenth century."),
  ("Plato's city has no rulers and Foucault's has one inspector.",
   "Plato's city is run by philosopher kings."),
  ('Plato is describing education and Foucault is describing punishment.',
   'Education is central to both, which is part of why she paired them.')],
 2, 'The arrangement is close to the same in both. The attitude toward it is where they part.'),

('Across weeks &middot; who doubts progress',
 'Three of the thinkers studied so far doubt that things are getting better. Which three, and about what?',
 [('Plato on whether writing improved memory, Aristotle on whether cities improve, Homer on the decline from a golden age.',
   'Three plausible-sounding doubts and none of them is an argument any of these three makes in this material.'),
  ("Rousseau on whether science and the arts improved anyone's morals, Kuhn on whether a revolution counts as progress, Foucault on whether the gentler prison is an improvement.",
   "Three different doubts about three different things, which is why they are worth holding as a set. Rousseau's is moral, Kuhn's is about the structure of knowledge, and Foucault's is about power. A question asking who resists the progress story could land on any of them."),
  ('Bacon on whether induction is reliable, Comte on whether the third stage arrives, Schlick on whether meaning can be checked.',
   "All three are on the progress side. Bacon is selling the method, Comte's three states are a progress story, and the Vienna Circle is building on both."),
  ('Copernicus on whether circles are real, Galileo on whether the Church was right, Newton on whether gravity explains everything.',
   'None of the three is making a claim about whether things improve over time.')],
 2, 'One doubt is about morals, one is about knowledge, one is about power.'),

('Kuhn &middot; what makes something a paradigm',
 "Kuhn's three worked examples of a paradigm are Newton's mechanics, Lavoisier's chemistry and Mendel's genetics. Plenty of good theories never become paradigms. What do these three have that a merely correct theory does not?",
 [('Each was proved true, where an ordinary theory is only well supported.',
   'Kuhn treats all three as replaceable, and two of them have been heavily revised since.'),
  ('Each gave the next generation a complete working kit, so people could stop arguing about what exists and what counts as a question, and get on with solving puzzles.',
   "That is the difference between a theory and a paradigm. Lavoisier's ideas about elements and the conservation of mass became the frame later chemists worked inside without reopening it every morning. A paradigm settles the questions underneath the questions. Normal science becomes possible once they are settled, and a revolution is expensive because it reopens them."),
  ('Each was the work of a single person, where most theories are built by groups.',
   "Authorship does nothing in Kuhn's account, and the three names are shorthand for whole bodies of work."),
  ('Each came from physics, chemistry and biology, so between them they cover the natural sciences.',
   'The spread across three sciences is a convenience of exposition and carries none of the argument.')],
 2, 'Ask what a field can stop doing once a paradigm is in place.'),

('Kuhn &middot; why you cannot explain by the ending',
 'A historian writes: Copernicus moved the sun to the centre because it led to modern astronomy. Kuhn says an explanation of that shape cannot work, whatever the subject. What is wrong with it?',
 [('Modern astronomy arrived three centuries after Copernicus, and an explanation has to name something that came before the thing it explains.',
   'A cause has to come first. The sentence offers an outcome from the 1700s onward as the reason for a decision made in the 1500s, which puts the cause after the effect. Kuhn\'s own wording is that events must follow their causes, so a sequence cannot be explained by the fact that it represents progress. It matters because this is the standard way the history of science gets written, and once it is ruled out the past stops being a set of steps toward us and becomes a set of other working systems. The fault has a name: <b>Whig history</b>.'),
  ('Copernicus was wrong about circular orbits, so his work did not lead to modern astronomy at all.',
   'He was wrong about the circles and the line of descent is real. The objection is to the shape of the explanation, and it would hold even if every fact in the sentence were right.'),
  ('Historians disagree about which developments count as progress, so the claim cannot be settled.',
   'Disagreement among historians is a different problem, and his objection would stand if every historian agreed.'),
  ('Science does not progress, so nothing can be explained by progress.',
   'He grants that normal science visibly accumulates. His objection is about which direction an explanation runs in.')],
 1, 'Write the two dates down and ask which one is supposed to be causing the other.'),

('Kuhn &middot; one word, two meanings',
 'Newton and Einstein both use the word mass. Why does that make the two theories hard to compare?',
 [('Einstein uses the word loosely and Newton uses it precisely.',
   'Both are precise. They are precise about different things.'),
  ('In Newton, mass is a fixed property of an object, the same whatever the object is doing.',
   "In Einstein it changes with velocity. So a sentence using the word is making two different claims in the two theories. Mass is conserved comes out true in one theory and false in the other, and the two sentences are not even disagreeing, because they are about different quantities. This is the first of Kuhn's three reasons for incommensurability, the one about meanings of terms changing, and it is the reason that gets attacked hardest."),
  ('Einstein proved Newton wrong about mass, so there is nothing to compare.',
   'Newtonian mechanics is still used daily, so the relation is more awkward than a refutation.'),
  ('The word is translated differently from the German.',
   'Not a translation problem between languages.')],
 2, 'Ask whether the quantity the word names stays put when the object starts moving fast.'),

('Foucault &middot; what the watching produces',
 'In a prison, an officer watches the inmates and writes reports, a senior officer reads the reports, and a governor reads the summaries. Foucault says an arrangement like that produces one thing, and he refuses to call it two things working together. What is it, and what phrase does he use for it?',
 [('Normalization, which he describes as the production of docile bodies.',
   'Both terms are real and neither is what watching in ranks is said to produce. Normalization is the goal the whole apparatus serves, and docile bodies are what discipline makes.'),
  ('Power-knowledge, which he describes as the development of force and the establishment of truth.',
   'Two outputs in one act: force grows and a truth gets fixed at the same moment. That is why he writes it with a hyphen. Two words joined by <i>and</i> would be two things that cooperate, and he means one thing with two faces. The reports are the truth about the inmate, and being the truth about him is what decides whether he goes home.'),
  ('The examination, which he describes as a ritual of power.',
   'The examination is one of the three techniques, alongside watching in ranks. It is a part of the apparatus and not what the apparatus produces.'),
  ('Discipline, which he describes as the art of distributions.',
   'Not a phrase from these lectures.')],
 2, 'His phrase has two halves joined by <i>and</i>, one about force and one about truth, which is the clue that he means a single thing.'),

('Foucault &middot; what the examination does',
 'Foucault names three techniques of control: watching arranged in ranks, judging a person against a norm, and the examination. The first two are separate jobs done by separate parts of an institution. What does the examination do?',
 [('It watches you and writes down a verdict about you in the same act.',
   'A school exam is the clean case. It observes your performance and produces a permanent record, in one sitting, and the record then follows you and decides what you are allowed to do next. Watching alone produces no file. Judging alone needs somebody else to have watched. The examination closes the loop, which is why it is the one that turns up in a clinic, a school and a prison alike.'),
  ('It punishes the body, where the other two only observe and rank.',
   'Physical punishment is what the modern apparatus replaced, and none of the three techniques involves it.'),
  ('It is entered voluntarily, where the other two are imposed.',
   'Nobody in his account chooses to be examined, and a school exam is a poor model of a voluntary act.'),
  ('It applies to whole groups, where the other two apply to one person at a time.',
   'The reverse. The examination is where a person is singled out and written down as an individual.')],
 1, 'Think about what a school exam physically does to you in one sitting, and what is left behind afterwards.'),

('Week 4 &middot; the portrait of a productive scientist',
 'One survey built a picture of the most productive scientist. Which detail was on the list?',
 [('Works evenings, collaborates widely, and avoids routine problems.',
   "Two of these are the reverse of the survey's findings."),
  ('Reserves mornings for writing, works on routinised problems, is detached from non-scientific social relations.',
   'Fox 1983. The list runs long and includes being driven, having a strong ego, tolerating ambiguity, being at home with abstractions, being relatively young, and having a prestigious mentor and a prestigious employer. Notice how much of it describes a situation and how little describes a person. That is why she printed the whole list.'),
  ('Is widely read outside science and keeps a broad social life.',
   'The survey says detached from non-scientific social relations.'),
  ('Avoids prestigious institutions in order to work undisturbed.',
   'Prestige of graduate school, mentor and employer are all on the list as positives.')],
 2, 'Half the list describes a personality and half describes a situation. The right answer has both kinds in it.'),

('Week 4 &middot; one figure against another',
 'In the United States in 2005, women earned 49 per cent of doctorates in the biological sciences and 18 per cent in engineering. What does the spread between those two figures rule out?',
 [('Any explanation resting only on something about women in general, since the same population faces both fields and the two numbers differ by nearly a factor of three.',
   'A claim about what women are like, or what women prefer, has to predict the same thing in biology and in engineering. It does not, so something about the fields themselves is doing the work. That is the move the whole lecture turns on, and it is why Rossiter looks at the status of a field and Barbercheck looks at how its advertisements talk.'),
  ('Any explanation appealing to discrimination, since discrimination would show up equally in both.',
   'Backwards. A difference between fields is what you would expect if the fields differ in how they treat women, and it is a problem for the general-trait story instead.'),
  ('The claim that biology counts as a science.',
   'Nothing in the figures bears on that.'),
  ('Nothing. The two fields are too different to be compared.',
   'They are both doctorates in a science in the same country in the same year, which is about as comparable as two figures get.')],
 1, 'Ask what a claim about women in general would have to predict about two different sciences in the same country in the same year.'),

('Week 4 &middot; the advertisements',
 'Advertisements in the journal <i>Science</i> pair the words simple and easy with pictures of women, and fast, reliable and accurate with pictures of men. Nobody placing those advertisements set out to make a claim about women in science. What makes the finding useful?',
 [('It shows that the advertisers held deliberate views about women.',
   'If it showed that, it would be weaker. A deliberate slight can be put down to the people who wrote it.'),
  ('It catches the association working where nobody chose it, inside the trade journal the field reads every week.',
   'The evidence is cheap and hard to argue with for exactly that reason. Nobody decided anything, and the pattern is there anyway, in the house organ of the profession. The study also found men more likely to be shown as heroes, as nonconformists, and at play, and women able to stand for nature in a way male figures could not.'),
  ('It shows that women prefer equipment that is simpler to operate.',
   'The words describe how the products are sold, and nothing in the study measures what anybody prefers.'),
  ('It shows nothing, since an advertisement makes no scientific claim.',
   'The claim being made is about the culture of the field, and an advertisement is evidence of culture precisely because it is not an argument.')],
 2, 'Ask what you can say about an association that nobody involved set out to create.'),

('Week 4 &middot; the drying agent',
 'A female doctoral student is quoted saying her colleagues went to parties with her but never asked her which drying agent to use. What does the quotation illustrate?',
 [('Direct hostility from supervisors.',
   'Her account describes friendly colleagues, and the usefulness of the quotation turns on that.'),
  ('Exclusion from the informal networks where technical knowledge moves, which leaves a person outside the working community while remaining inside the social one.',
   'Etzkowitz and colleagues, 2000. Nobody refused her anything. It simply never crossed their minds to ask her a technical question, so she was never part of the exchange that makes somebody a colleague. That is the kind of difference each instance of which looks trivial and which compounds.'),
  ('A formal policy barring women from laboratory work.',
   'No policy is involved, which is the point.'),
  ('A difference in training between men and women.',
   'Her training is the same; the asking is what differs.')],
 2, 'Notice that everyone in the story is being perfectly friendly.'),

('Week 4 &middot; do women learn differently',
 'Some feminists and non-feminists have argued that men and women tend to think differently. What was the claim, and who made it?',
 [('Gilligan and Keller, that women tend to think in more concrete terms and are better served by problem-centred learning.',
   'Gilligan 1982 and Keller 1985. Hold it apart from the maths gene claim, which the lecture rejects outright because genes only act in environments. This one is treated as a live proposal about learning styles and it comes from inside feminism as well as outside it.'),
  ('Benbow and Stanley, that boys have an inborn advantage in mathematics.',
   'That is the maths gene claim, which she rejected as an ideological statement, meaning one that states a political position while dressed as a finding.'),
  ('Rossiter, that women prefer the invisible sciences.',
   "Rossiter's argument is that women were pushed into them."),
  ('Lawrence Summers, that women are less willing to work long hours.',
   'The Harvard episode, and a different claim from the one about learning patterns.')],
 1, 'Two different claims about men and women appear in that lecture. One she rejects flatly, and one she reports as a live proposal.'),

('The course thesis',
 'PHI2394 is built around one claim about the scientific method. What is it?',
 [('Science progresses by accumulating facts.',
   'The view the whole term is built against.'),
  ('The scientific method is not fixed, and it is socially constructed.',
   'Every week is a stage in that argument. Week 2 shows the method changing across two thousand years, week 3 shows it changing shape in a revolution, and week 4 says what it is made of. If an exam question asks what ties the course together, this is the sentence.'),
  ('Science and religion are compatible.',
   'Lynn White touches on it and it is not the thesis.'),
  ('Scientific knowledge is impossible.',
   'Nothing in the course argues that, and week 4 ends by crediting laboratories with objectivity.')],
 2, 'One sentence, in two halves, and the whole term is an argument for it.'),

('Across weeks &middot; putting ideas in order',
 'Four claims, from four different thinkers. Which was made first?',
 [('The claim that power and knowledge are one thing.',
   'Foucault, 1975.'),
  ('The claim that knowing how a thing works gives you power over it.',
   'Bacon, around 1600, roughly 375 years earlier. The order matters, because the later claim is built on the earlier one and reverses its verdict. Getting the order backwards makes the relationship impossible to state.'),
  ('The claim that paradigms are incommensurable.',
   'Kuhn, 1962.'),
  ('The claim that a norm sorts citizens into normal and abnormal.',
   'Foucault again.')],
 2, 'Three of these four belong to the twentieth century.'),

('Across weeks &middot; telos, three times',
 '<i>Telos</i> turns up in three different arguments. Which set is right?',
 [('Aristotle proposes it, Bacon attacks it, and Kuhn says foundationalism works differently from it.',
   'Aristotle: everything has an end it grows toward. Bacon: that makes the world something you wait to receive, so he wants experiment instead. Kuhn: a foundation pushes up from below, while <i>telos</i> pulls from ahead. One Greek word doing work in three centuries that are two thousand years apart.'),
  ('Plato proposes it, Aristotle attacks it, and Foucault revives it.',
   "It is Aristotle's term, and Foucault does not use it."),
  ('Bacon proposes it, Rousseau attacks it, and Comte revives it.',
   'None of those three owns the term.'),
  ('It appears only in the Aristotle lecture.',
   "She brought it back twice: in Bacon's objection, and in the Kuhn lecture on foundationalism.")],
 1, 'One man coins it, one man attacks it, and one man uses it to explain what his own idea is not.'),

('Across weeks &middot; what the plague town and the panopticon share',
 "Foucault puts the plague town and Bentham's building in the same chapter. What do they have in common?",
 [('Both are nineteenth-century French institutions.',
   'The plague measures are older and Bentham was English.'),
  ('Both are responses to disease.',
   'The panopticon is a prison design.'),
  ('Both are arrangements where order reaches into the smallest details of daily life and each person is placed, watched and sorted.',
   "The plague town does it with an emergency as the excuse and the panopticon does it with architecture, permanently. That is his argument in one move: the emergency measure became the ordinary design. The plague's political dream is strict division and regulation reaching the smallest details, and the building delivers exactly that with nobody needing to be in the tower."),
  ('Both were proposed by Bentham.',
   'The plague measures predate him by centuries.')],
 3, 'One is a temporary emergency and one is a permanent building. Ask what they are both doing to the people inside.'),
]
