# Question bank, week 2. Every item comes from the professor's posted notes for
# 14 and 16 September, or from the lecture recording of 14 September.
# Shape: (topic, question, [(option, why) x4], answer index starting at 1, hint)

WEEK2 = [
("Plato &middot; the text, the author, the dialogue",
 "The allegory of the cave comes from which text, and who are the two speakers in it?",
 [("The <i>Apology</i>, a conversation between Socrates and his accuser Meletus.",
   "The <i>Apology</i> is Socrates on trial. No cave in it."),
  ("The <i>Republic</i>, a conversation between Glaucon and Socrates.",
   "Book seven of the <i>Republic</i>. Glaucon is the one being walked through the cave. She said there is a question on the text, the author and the name of the dialogue, so hold three facts: Plato wrote it, the dialogue is the <i>Republic</i>, and Plato never speaks in his own voice anywhere."),
  ("The <i>Symposium</i>, a conversation between Socrates and Alcibiades.",
   "The <i>Symposium</i> is the drinking party about love."),
  ("The <i>Timaeus</i>, a conversation between Socrates and Critias.",
   "The <i>Timaeus</i> is Plato's account of how the cosmos was made.")],
 2, "Plato wrote twenty-six dialogues. This one is his long work about the ideal city."),

("Plato &middot; what education is",
 "Plato writes that education is not &ldquo;putting knowledge into souls that lack it, like putting sight into blind eyes&rdquo;. So what is it?",
 [("Filling the student with the knowledge the teacher already has.",
   "This is the exact thing the quoted line rejects."),
  ("Training in a craft, until the hands know what to do without being told.",
   "That is skill at making or doing something, which the Greeks called <i>techne</i>, and Plato ranks it below the knowledge he is after here."),
  ("Turning the soul around, so that it looks toward the light.",
   "Her phrase on the slide was that education is turning around. The eyes already work. They are pointed at the wall. Sight is no good if you are not looking in the right place."),
  ("Memorising the dialogues until the arguments can be reproduced.",
   "Nothing in the lecture supports this, and it is the opposite of a method of inquiry.")],
 3, "If the eyes are not broken, what is the problem with them?"),

("Plato &middot; the Kalliopolis",
 "Beside Foucault's &ldquo;panoptic utopia, the utopia of a perfectly governed city&rdquo;, the professor wrote on her own slide: &ldquo;think Plato, <i>Republic</i>, the Kalliopolis&rdquo;. What is the Kalliopolis, and why is it there?",
 [("The cave itself, because both Plato and Foucault describe people who cannot see their own confinement.",
   "Tempting, and the one to beware of. The Kalliopolis is a city, and the cave is a separate image."),
  ("The Athenian democracy Plato lived under, which Foucault treats as the first disciplinary society.",
   "Plato's Kalliopolis is his own invention, and he is against Athenian democracy."),
  ("Plato's ideal city, ruled by philosophers, where correct education is central, which is the same dream of a perfectly ordered city that Foucault finds in the plague town.",
   "<i>Kalli</i> means beautiful, so the most beautiful city. Foucault says the plague town has a political dream of strict division and regulation reaching into the smallest details of daily life. Plato wrote the attractive version of that dream."),
  ("Plato's name for the realm of the Forms, which Foucault treats as the model for the inspector's tower.",
   "The realm of the Forms is transcendental, and it is not a city.")],
 3, "<i>Kalli</i> is the Greek for beautiful. <i>Polis</i> is the Greek for city."),

("Plato against Aristotle &middot; which theory matches which philosopher",
 "Plato and Aristotle both use the word form. What is the difference?",
 [("Plato puts form in the object; Aristotle puts it in a realm outside ours.",
   "The right distinction with the names swapped, and the commonest way to lose this mark."),
  ("Plato puts the Forms in a transcendental realm outside ours; Aristotle puts form in the thing itself, together with the goal it is growing toward.",
   "The consequence is what to remember. Because Aristotle keeps form in the dog and the tree, he can go and dissect them, which is why she called him the first biologist. Plato's theory points away from the physical world."),
  ("Plato means the shape of a physical object; Aristotle means the definition of a word.",
   "Neither of them means shape, and neither means a definition."),
  ("They mean the same thing, and the disagreement is only about how we come to know it.",
   "The disagreement is about where the form is, which is a disagreement about what exists.")],
 2, "One of the two could do biology. Which one, and why does that follow from where he puts form?"),

("Aristotle &middot; what form answers",
 "In the lecture, Aristotle's form and <i>telos</i> are offered as his answer to a question. Which question?",
 [("How can we be sure our senses are telling us the truth?",
   "That is the question put at the centre two thousand years later by Bacon and the <b>empiricists</b>, meaning the people who hold that knowledge starts in the senses."),
  ("What makes a city just?",
   "That is the <i>Republic</i>."),
  ("What causes movement, and where do things come from?",
   "The question the whole Greek picture is organised around, and she said so twice. <i>Physis</i> implies movement. Plato answers with the Forms in a realm outside ours, Aristotle with form in the thing and a goal it moves toward."),
  ("Is technology part of nature or separate from it?",
   "That is Schadewaldt's question about <i>physis</i> and <i>techne</i>.")],
 3, "<i>Physis</i> was defined in the lecture as implying one particular thing. What was it?"),

("Aristotle &middot; what is critical to him",
 "<i>Telos</i> is the term she stressed as critical to Aristotle. What does it mean?",
 [("The end or goal of each living thing, meaning that everything has an intended purpose it is growing toward.",
   "The word literally means end. Track it: Bacon attacks it as his central objection to Aristotle, Kuhn says history cannot be explained by what it led to, and she said explicitly that the idea of knowledge resting on a firm bottom layer, which is called <b>foundationalism</b>, works differently from <i>telos</i>."),
  ("The material a thing is made out of.",
   "That is matter, which is the thing form is contrasted with."),
  ("The distance between an appearance and the reality behind it.",
   "Closer to Plato's cave. The word itself comes from elsewhere."),
  ("The method of separating opinion from knowledge.",
   "That is dialectic, and it is Plato's.")],
 1, "The word survives in English in <i>teleology</i>."),

("The era question that is really about the person",
 "Which of these is true of Aristotle?",
 [("He was born in Athens to an aristocratic family and founded a school called the Academy.",
   "Every word of this is Plato. She set the trap by giving both biographies together."),
  ("He wrote twenty-six dialogues in which he never speaks in his own voice.",
   "Plato again."),
  ("He lived roughly a century after Bacon and was influenced by the Scientific Revolution.",
   "Aristotle is 384 to 322 BCE and Bacon is 1561 to 1626 CE, so this is about two thousand years late."),
  ("He was born in Stagira, was never an Athenian citizen, studied with Plato, and tutored Alexander the Great.",
   "384 to 322 BCE, and she called him the first biologist. The non-citizenship is why he had to leave Athens at the end of his life.")],
 4, "Two of these four describe Plato's life."),

("Schadewaldt &middot; physis and techne",
 "What is the difference between <i>physis</i> and <i>techne</i>?",
 [("<i>Physis</i> is the study of nature and <i>techne</i> is the study of tools, so they are two branches of one subject.",
   "Neither word names a field of study. They name two kinds of thing in the world."),
  ("<i>Physis</i> is nature, the creative origin that everything grows out of; <i>techne</i> is made by people, and is a combination of man and nature.",
   "<i>Physis</i> is the origin and centre of all activity and it implies movement, which is why it answers the question about what causes things to move. Schadewaldt's whole complaint is that modern science pulled the two apart."),
  ("<i>Physis</i> is what can be measured and <i>techne</i> is what cannot.",
   "Reduction to the measurable is the modern move Schadewaldt attacks, so this puts his target into his own vocabulary."),
  ("<i>Physis</i> is the body and <i>techne</i> is the soul.",
   "No part of the lecture maps them onto body and soul.")],
 2, "One of the two is where everything comes from. The other needs a person involved."),

("Schadewaldt &middot; where techne belongs",
 "Schadewaldt places <i>techne</i> between two other kinds of knowing. Which two, and what makes <i>techne</i> different from the higher one?",
 [("Between <i>doxa</i> and <i>dialektike</i>. <i>Techne</i> differs because it can be taught.",
   "<i>Doxa</i> is opinion and dialectic is Plato's method. Neither is in the quoted passage."),
  ("Between <i>empeiria</i>, mere experience or know-how, and <i>episteme</i>, theoretical knowledge. <i>Techne</i> differs because <i>episteme</i> concerns what is immutable and primary, while <i>techne</i> bears on what is mutable and in the process of becoming.",
   "The passage she quoted from page 29. <i>Techne</i> is productive knowledge, so it works on things that are still changing. So it ranks below <i>episteme</i> and above raw experience."),
  ("Between <i>physis</i> and <i>telos</i>. <i>Techne</i> differs because it has no goal of its own.",
   "<i>Physis</i> and <i>telos</i> are not kinds of knowing."),
  ("Between craft and art. <i>Techne</i> differs because it produces useful things.",
   "Both English words translate <i>techne</i> itself, so this is circular.")],
 2, "One Greek word means plain experience. The other is the root of the English word <i>epistemology</i>."),

("Schadewaldt &middot; atechnia",
 "What is <i>atechnia</i>?",
 [("The refusal to use technology at all.",
   "The word names a failure of knowledge. Nobody in it is refusing to act."),
  ("Knowledge that is productive and rich, but which has a false idea of the thing itself: a blunder.",
   "Her gloss on the slide was that <i>atechnia</i> is a false idea of the thing, held confidently. Note that it can be rich and diverse and still be a blunder, which is the uncomfortable part."),
  ("The loss of a craft when nobody is left who can practise it.",
   "Not a claim in the lecture."),
  ("Nature acting without human involvement.",
   "That is <i>physis</i>.")],
 2, "The prefix <i>a</i> means without. What is it without, given the knowledge in question still works?"),

("Schadewaldt &middot; what Wolfgang said",
 "Schadewaldt says the modern conception of nature has been &ldquo;extraordinarily successful&rdquo; and has cost us something. What is his complaint?",
 [("That science has produced weapons, so the problem is what the knowledge gets used for.",
   "His argument is about the conception of nature itself, before anyone applies it."),
  ("That scientists no longer read the Greeks, so the tradition has been forgotten.",
   "A plausible thing for a classicist to say. He says something else: the loss he names is in the concept."),
  ("That nature has been reduced to what is calculable, which splits thought from extension, nature from spirit, and subject from object, and leaves an impoverishment that is hard to estimate.",
   "His word is dualism, meaning a split into two things the Greeks held as one. <i>Physis</i> held form and motion, law and life, causality and purpose together. Keeping only the calculable half works extremely well and drops the rest."),
  ("That modern science makes claims it cannot prove, because induction never justifies a general law.",
   "A real problem, and a different one. Watch a thousand swans, see that every one is white, and conclude that all swans are white. The conclusion covers every swan there has ever been, and you looked at a thousand, so the thousand can never make it safe. Europeans believed exactly that until a Dutch expedition reached Western Australia in 1697 and found black ones. Reasoning upward from particular cases to a general law like that is called <b>induction</b>, and that gap in it is the problem of induction. It bites Bacon, whose whole method runs on it, and it bites the idea that every claim rests on a lower claim down to a bottom layer that needs no reason under it, which is called <b>foundationalism</b>.")],
 3, "He praises the results in the same sentence as the complaint. So the complaint concerns what got left out."),

("Schadewaldt &middot; the solution",
 "What does Schadewaldt propose as the way out of that dualism?",
 [("Stop using mathematics to describe nature.",
   "He calls the calculable approach extraordinarily successful. He wants to add to it."),
  ("Give the humanities authority over what the sciences are allowed to study.",
   "Nothing in the lecture proposes a change of authority."),
  ("Replace <i>techne</i> with <i>episteme</i>, so that knowledge is theoretical again.",
   "The split he attacks runs between nature and <i>techne</i>, so swapping one Greek word for another does not close it."),
  ("Return man, as the observing subject, back into the act of inquiring into nature.",
   "The dualism puts the observer outside what is observed, so the fix puts the observer back inside it. Carry this past the exam: weeks 5 and 6 make the same move under new names, situated knowledge and standpoint theory.")],
 4, "A dualism separates two things. Which two does he most want rejoined, given he keeps praising the results?"),

("The Greeks &middot; Heraclitus",
 "She quoted Heraclitus, sixth century BCE: sound thinking is man's greatest power, and his highest aptitude is that he can say what is and &ldquo;fashion creatively by hearkening to nature&rdquo;. What was her one-line summary of him?",
 [("Nature is in harmony.",
   "Her summary line, written under the quotation. It matters because it is the background assumption Plato and Aristotle are both working against: there is an order out there, and thinking well means listening to it."),
  ("Everything is in flux.",
   "The famous Heraclitus line about stepping into the same river twice. She used a different one."),
  ("Man is the measure of all things.",
   "Protagoras."),
  ("The unexamined life is not worth living.",
   "Socrates, in the <i>Apology</i>.")],
 1, "Hearkening means listening. What does the quotation assume is out there to be listened to?"),

("Plato &middot; who is speaking",
 "She stressed one point about how to read the dialogues. Which?",
 [("Socrates wrote nothing, so the dialogues are our only record of his real views.",
   "The opposite of her point. She said Socrates was a real person, and this is Plato's Socrates."),
  ("Plato does not speak in his own texts. Socrates was a real person, but the Socrates in the dialogues is Plato's.",
   "Which means you can never quote a line as Plato's own opinion. It is a character's. She ran the Academy point alongside it: twenty-six dialogues, and a school."),
  ("The dialogues were written down by students from memory.",
   "Not claimed anywhere in the lecture."),
  ("Each dialogue is set in a different city, so the arguments are local.",
   "Not a claim she made.")],
 2, "Count how many times Plato uses the word <i>I</i> in the <i>Republic</i>."),

("Plato &middot; dialectic",
 "What is dialectic, in Plato?",
 [("A debate in which two speakers argue opposite sides to entertain an audience.",
   "That is closer to the sophists, whom Plato is attacking."),
  ("The Platonic method of inquiry, the best way to get to the truth, and the process of separating opinion from knowledge and understanding.",
   "Her definition. It is a method, which is why it belongs in a course on scientific method: Plato's answer to the question of how you find out anything at all. The cave is the picture of it, and dialectic is the procedure."),
  ("The historical process by which one idea gives rise to its opposite.",
   "Hegel and Marx, and about two thousand years later."),
  ("The ranking of the crafts below theoretical knowledge.",
   "A conclusion Plato reaches. The question asks for the method he reaches it by.")],
 2, "Two of these four are real meanings of the word from other centuries. Which one is the one she defined?"),

("Plato &middot; philosopher kings",
 "Why should philosophers rule, and what does their education require?",
 [("Because they are the only ones who want power, and their education requires rhetoric and law.",
   "Plato's point is close to the reverse: the people fit to rule are the ones not hungry for it."),
  ("Because they are awake while everyone else is dreaming, and their education needs geometry and astronomy.",
   "Her quotation described them exactly that way. The geometry and astronomy matter: for Plato mathematics is a way to gain access to the abstract, which is the contrast she later drew with Bacon, for whom mathematics predicts what physical bodies will do."),
  ("Because they are the wealthiest class and can afford to govern without payment.",
   "Not a claim in the lecture."),
  ("Because they have left the cave and will not return to it.",
   "In the allegory the one who has left is made to go back down.")],
 2, "The subjects are the two that deal in things you cannot touch."),

("Metaphysics &middot; where the word comes from",
 "The lecture explained where the word metaphysics comes from. What is the explanation, and what does the field ask?",
 [("From the Greek for beyond nature, because the subject deals with what is supernatural.",
   "The popular explanation, and she gave the other one. The supernatural never comes into it."),
  ("From the title of Aristotle's book, which compilers placed after his <i>Physics</i> in the order of the works. The field asks what the origin and nature of all things in the cosmos are, and how we investigate them.",
   "A filing decision became the name of a discipline. Worth having, because it is a small concrete case of the course thesis: a category in science got its name from a filing accident. The subject's own nature had nothing to do with it."),
  ("From Plato's Academy, where it named the final year of study.",
   "Not claimed anywhere."),
  ("From the Latin for the study of first causes, coined in the Middle Ages.",
   "The word is Greek and predates the Middle Ages.")],
 2, "<i>Meta</i> here means after. After what, and in what sense of after?"),

("Who Francis Bacon is",
 "Which description fits Francis Bacon?",
 [("Early modern philosopher, 1561 to 1626, the father of empiricism, strongly influenced by the Scientific Revolution.",
   "Empiricism means the senses are the original source of knowledge, from the Greek <i>empeiria</i>, experience. Its opposite is the view that reason alone gets you there, which is Plato. Bacon's version has teeth because he adds experiment."),
  ("The astronomer who found that the planets revolve around the sun.",
   "Galileo, 1564 to 1642, whom she used as her contrast to Bacon's complaint about Aristotle."),
  ("The philosopher who argued that a return to Greek values was necessary for society and education.",
   "Rousseau, 1712 to 1778."),
  ("The historian who argued that Christian ideas about work shaped Western technology.",
   "Lynn White Jr.")],
 1, "The word for his position comes from the Greek <i>empeiria</i>, experience."),

("Which theory matches which philosopher",
 "In Bacon's simile, the ant, the spider and the bee stand for three ways of working. Who is the spider?",
 [("The alchemists, who only store things up and use them.",
   "That is the ant. Bacon calls them the empirics: they collect, and nothing happens to what they collect."),
  ("The proper natural philosopher, who gathers material and then digests it.",
   "That is the bee, and it is the one Bacon wants you to be."),
  ("The Aristotelians, who spin webs out of their own entrails.",
   "The dogmatists, in Bacon's word. The insult is precise: they produce elaborate systems out of themselves and take nothing in from the world. Ant collects and does not think, spider thinks and does not collect, bee does both. From <i>Novum Organum</i> I.95, quoted in full on her slide."),
  ("The Greeks, who let ethics and politics dominate philosophy.",
   "A real Bacon complaint, and a separate one.")],
 3, "Where does a spider's web physically come from?"),

("Bacon against Aristotle",
 "What exactly was Bacon's problem with the Aristotelian worldview?",
 [("That Aristotle relied on observation, and observation is unreliable.",
   "Backwards. Bacon is the one insisting on observation."),
  ("<i>Telos</i>: a fundamental order that has to be understood, with the world revealing itself to the observer who waits for it.",
   "If everything already has a purpose built in, your job is to receive the order. Bacon wants you to go and get it, by experiment, which is why knowledge turns into power over the physical world."),
  ("That Aristotle placed the Forms in a realm outside this one.",
   "Plato's position, and the standard mix-up."),
  ("That Aristotle said nothing about method.",
   "His objection is to the method Aristotle has. An absence of method is a different charge.")],
 2, "Bacon was also critical of the alchemists. What do the Aristotelians and the alchemists have in common, in his eyes?"),

("Bacon &middot; his complaint about the ancients",
 "What did Bacon say had gone wrong with philosophy in Greece and Rome?",
 [("Ethics and politics dominated philosophy, with the consequence that natural philosophy performed the role of a servant.",
   "Her wording. The charge is about rank: studying nature was treated as a junior subject that served the questions people really cared about. Bacon wants it at the centre, because it is the part that produces power over the physical world."),
  ("They had no mathematics capable of describing motion.",
   "Not his complaint, and the Greeks had a great deal of mathematics."),
  ("They wrote in dialogue form, which hides the author's own view.",
   "A fair observation about Plato and not a Bacon complaint."),
  ("They relied on experiment without any theory to guide it.",
   "That is his charge against the alchemists, the ants.")],
 1, "He is making a claim about which subject was treated as more important than which."),

("The Middle Ages &middot; Lynn White Jr.",
 "What is Lynn White's argument about technology in the Middle Ages?",
 [("Technology advanced once the Church lost its authority over learning.",
   "He argues the opposite: the religious worldview is the engine."),
  ("New tools arrived from outside Europe and changed how Europeans thought about God.",
   "The causal arrow in his argument runs from the worldview to the technology."),
  ("Technological change is driven by economic need, and religion follows along behind it.",
   "The position his argument is written against."),
  ("Religious worldviews shape which technologies get developed, and the Judaeo-Christian picture made work itself a form of worship.",
   "His chain: God is a creator and an architect, man is made in his image and told to rule the world as a creative cooperator, and Christian history runs in one direction toward a goal, so there is no time to lose. Therefore manual work is an essential and pressing form of worship.")],
 4, "Which way does the causation run in his argument, from belief to tools or from tools to belief?"),

("The Middle Ages &middot; Deism",
 "Around 1300, she said, the first ideas of Deism start to develop. What is the picture, and why does it matter for science?",
 [("God as a clockmaker who set the world in motion, which makes studying the mechanism a pious act.",
   "Once God winds the world up and steps back, the world is a mechanism, and taking it apart to see how it runs becomes a way of admiring the maker. That is how a religious worldview ends up licensing mechanical science."),
  ("God as a judge who intervenes constantly, which makes natural law impossible.",
   "This is the view Deism moves away from."),
  ("The denial that God exists, which frees science from the Church.",
   "Deism is not atheism. There is a maker in the picture."),
  ("The claim that the world is eternal and had no beginning.",
   "That is closer to Aristotle, and it is what Christian thought rejected.")],
 1, "The usual image for it is a piece of machinery that keeps running after you wind it."),

("Which theory matches which philosopher",
 "Which claim is Rousseau's?",
 [("A return to Greek values is necessary for society and education, and progress is only possible through education.",
   "1712 to 1778, French, shaped by the Enlightenment and the French Revolution. He is the counter-current in the week: an Enlightenment figure doubting that progress in the sciences and arts improved anyone's morals. His line that barbarous people are those who lack virtue is tied straight back to Plato, Socrates and Aristotle."),
  ("The senses are the original source of knowledge.",
   "Bacon."),
  ("Explanation passes through three historical stages before it becomes scientific.",
   "Comte, from the week 2 packet."),
  ("Power and knowledge are one thing, aimed at controlling what we know.",
   "Foucault.")],
 1, "He is the one in this week who looks backwards for his model."),

("The era question",
 "Put these four in the order they worked, earliest first: Bentham, Copernicus, Rousseau, Bacon.",
 [("Bacon, Copernicus, Rousseau, Bentham",
   "Copernicus dies in 1543, eighteen years before Bacon is born."),
  ("Copernicus, Bacon, Rousseau, Bentham",
   "1473 to 1543, 1561 to 1626, 1712 to 1778, 1748 to 1832. Her detail standard means centuries are enough: Copernicus is late fifteenth into the sixteenth, Bacon straddles 1600, and Rousseau and Bentham overlap in the eighteenth."),
  ("Copernicus, Rousseau, Bacon, Bentham",
   "Rousseau is born eighty-six years after Bacon dies."),
  ("Bacon, Rousseau, Copernicus, Bentham",
   "Copernicus is the earliest of the four, and this puts him third.")],
 2, "One of the four died before the other three were born."),
]
