# Question bank, week 3. Every item comes from the professor's posted notes for
# 21 and 23 September. Foucault then Kuhn.

WEEK3 = [
("Foucault &middot; Discipline and Punish",
 "<i>Discipline and Punish</i>, 1975, is described as a genealogical study of what?",
 [("Why punishment became harsher over time.",
   "His account runs the other way. The modern method is gentler, and that is what he finds worth explaining."),
  ("The development of the gentler modern way of imprisoning criminals, in place of torturing or killing them.",
   "Genealogical means tracing how a practice came to be, without assuming it was an improvement. The puzzle he sets himself: punishment really did get gentler, so what is the new method doing that the old one could not?"),
  ("The origins of the French legal system.",
   "The book ranges across Europe and is not a legal history."),
  ("How prisons fail to reduce crime.",
   "A twentieth-century policy question. His is different.")],
 2, "The word gentler is in her note, and it is the thing he finds suspicious."),

("Foucault &middot; power-knowledge",
 "Foucault says hierarchical observation leads to power-knowledge, which he glosses as &ldquo;the development of force and the establishment of truth&rdquo;. Whose slogan is he building on?",
 [("Plato, that the philosopher should rule.",
   "Plato grounds power in knowledge of the Forms, which is a different relation: knowing comes first and earns the right to rule."),
  ("Rousseau, that progress comes through education.",
   "Not a claim about power."),
  ("Bacon, that knowledge is power.",
   "Bacon meant power over the physical world, and he meant it as a promise. Foucault keeps the identity and turns it into an accusation: power and knowledge have the same goal, which is controlling what we know. Same three words, opposite verdict."),
  ("Bentham, that institutions should maximise happiness.",
   "Bentham held that the right action is whichever one produces the greatest happiness for the greatest number, and the name for that doctrine is <b>utilitarianism</b>. It says what an institution should aim at. It says nothing about whether knowing someone and controlling them are the same act.")],
 3, "The phrase is three words long and it belongs to someone from week 2."),

("Foucault &middot; docile bodies",
 "What is a docile body?",
 [("A prisoner who has accepted guilt.",
   "Docility here is about usefulness. Remorse is a separate matter."),
  ("A body made useful and easier to control by disciplinary power: prisoners, soldiers, workers, schoolchildren.",
   "The list matters, because it shows how far past the prison the argument reaches. The same technique runs in a barracks, a factory and a classroom. Discipline produces docile bodies, which is why the prison is a model and not an exception."),
  ("A body that has been physically weakened by confinement.",
   "Discipline makes the body more capable."),
  ("A citizen who obeys the law without needing to be watched.",
   "Close, and it misses the production. The point is what makes the body that way.")],
 2, "Her list of examples had four items and only one of them was a prisoner."),

("Foucault &middot; the body as machine",
 "Under discipline the human body becomes a machine whose functioning can be optimized, calculated and improved. By what procedure?",
 [("By medical intervention and surgery.",
   "No surgery in the passage."),
  ("By measuring it against the average body in the population.",
   "Measuring every person against a norm and sorting them by it is what she calls <b>normalization</b>, and it is a real part of the lecture. It is not the mechanism described in this quoted passage."),
  ("By breaking its functions, movements and capabilities into narrow segments, analysing them in detail, and recomposing them in a maximally effective way.",
   "Break down, analyse, recompose. Think of a drill sergeant decomposing a rifle reload into numbered motions, or a factory time-and-motion study. The body is treated as something that can be taken apart on paper and reassembled better."),
  ("By training it to withstand pain.",
   "That belongs to the older regime of punishment the book describes the end of.")],
 3, "Three verbs in sequence, and the same three an engineer would use on a mechanism."),

("Foucault &middot; normalization",
 "What is normalization, and what does Foucault say it produces?",
 [("The return of a disturbed person to health, which produces recovery.",
   "The everyday medical sense of the word. His use is different."),
  ("The goal of disciplinary power, which produces judicial systems sorting citizens into normal and abnormal.",
   "She called it the goal, which is the word to hold. Everything else in the apparatus serves it. Once a norm exists, every person can be placed against it, and the placement is itself a judgment."),
  ("The standardisation of laws across a country, which produces equality before the law.",
   "Not a claim in the lecture."),
  ("The spread of scientific method into the social sciences, which produces objectivity.",
   "Not his argument.")],
 2, "She used one word for its status in the system, and that word was not technique."),

("Foucault &middot; normalization in practice",
 "Where does normalization operate, away from prisons and courts?",
 [("Prisons, armies and asylums.",
   "All Foucault subjects. She gave a different list for this term."),
  ("Courts, police and parliaments.",
   "Institutions of law, and normalization works outside the law."),
  ("Standardized education programmes, medical practices, industrial processes and production.",
   "Notice that none of them is a prison. That is the point of the list: the technique that was visible in the prison is running in a school timetable and a production line, where nobody experiences it as punishment."),
  ("Census-taking, taxation and conscription.",
   "State functions. She named others.")],
 3, "Her examples were all places nobody is being punished."),

("Foucault &middot; the plague town",
 "<i>Panopticism</i> opens with the plague town. What does Foucault say the plague is met with?",
 [("Flight, since those who could leave the city did.",
   "Historically common. His subject is different."),
  ("Prayer and religious explanation.",
   "Not the response he analyses."),
  ("Order: sorting out the disease and separating bodies, sorting out evil, which increases fear and death.",
   "The order is the response, and the last clause is the sting: the sorting makes the fear and the death worse. The plague is the occasion where a town gets to organise itself completely, and Foucault uses it to show what total organisation looks like when it is allowed."),
  ("Medical experiment, since the epidemic gave doctors material.",
   "Not in the text.")],
 3, "His answer is a single word, and the surprise is what he says it produces."),

("Foucault &middot; the political dream",
 "Foucault says the plague has a &ldquo;political dream&rdquo;. What is it?",
 [("That the state should take over medicine.",
   "Not the dream he names."),
  ("A strict division, and the penetration of regulation into even the smallest details of everyday life.",
   "Two halves, and the second is the one that matters: regulation reaching the smallest details. A plague gives authorities a reason to say where every person may stand and at what hour, and Foucault's claim is that this is attractive to power independently of the disease."),
  ("That the city should be rebuilt on rational principles.",
   "Architecture comes later in the text, with the panopticon."),
  ("That the healthy and the sick should be treated as equals.",
   "The opposite of the division he describes.")],
 2, "This is the entry she annotated with Plato and the Kalliopolis."),

("Foucault &middot; spaces of exclusion",
 "What are the spaces of exclusion, and what is the problem with them?",
 [("Prisons, and the problem is that they do not reform anyone.",
   "A policy complaint. His argument runs elsewhere."),
  ("Borders, and the problem is that they are arbitrary.",
   "Not discussed."),
  ("Places for beggars, vagabonds, madmen and the disorderly, and the problem is that they are formed by the real population while authority works through a binary of division and branding.",
   "Her example was the nineteenth-century psychiatric asylum. The binaries she listed: mad against sane, dangerous against harmless, normal against abnormal. The problem is that real and varied people get sorted by a two-way switch, and then treated as the side of the switch they were assigned to."),
  ("Private property, and the problem is that it excludes the poor from land.",
   "Not his argument here.")],
 3, "Her example for it was an institution from the nineteenth century."),

("Foucault &middot; the modern prison",
 "What does the modern prison do to an inmate? Two things, and the second is the one people forget.",
 [("It deprives inmates of liberty, and it categorizes their nature.",
   "The second half is the part people forget and the part that carries the argument. Losing your liberty is the punishment. Having your nature written down and filed is the new thing, and it is what links the prison to the clinic and the school."),
  ("It punishes the body, and it saves the soul.",
   "The older religious model."),
  ("It removes the criminal from society, and it deters others.",
   "The standard justification. Her formulation is different."),
  ("It separates the dangerous from the harmless, and it releases the reformed.",
   "Division and branding is a different point in the lecture.")],
 1, "One half is about what is taken away. The other is about what is written down."),

("Foucault &middot; the building itself",
 "In Foucault's description of the building, how many windows does each cell have, and why?",
 [("One, facing the tower, so the inmate can be seen.",
   "The obvious design, and it would leave the cell too dark to see into."),
  ("Two, one facing the tower and one on the outside, so the light crosses the cell from one end to the other.",
   "The detail is the whole trick. Backlighting turns every inmate into a visible silhouette from the tower. The architecture does the surveillance, which is why one person can replace many."),
  ("None, so the inmate is in darkness and the tower is lit.",
   "This would make the inmate invisible, which defeats the design."),
  ("Two, both facing outward, so the inmate cannot see the tower at all.",
   "The inmate has to be able to see the tower, because the uncertainty about it is the mechanism.")],
 2, "Think about what you need behind a person for them to appear as a clear outline."),

("Foucault &middot; the royal menagerie",
 "Foucault writes that the Panopticon is a royal menagerie in which three things have been replaced. Which three?",
 [("The cage by the cell, the keeper by the guard, the visitor by the inspector.",
   "A tidy-sounding list and not his."),
  ("The animal by man, individual distribution by specific grouping, and the king by the machinery of a furtive power.",
   "A menagerie was a royal collection of animals, arranged so one person could view them all. Foucault's three swaps turn it into a prison: the exhibit is now a person, the arrangement is now by category, and the viewer is now a machine with nobody in particular at the centre. Furtive means hidden."),
  ("The garden by the yard, the spectacle by the record, the crowd by the individual.",
   "Not his wording."),
  ("The animal by the criminal, the king by the state, the menagerie by the prison.",
   "Half right on the first, and the middle term and the third are wrong.")],
 2, "A menagerie is a royal zoo. Ask what each of its three parts turns into."),

("Kuhn &middot; the break with positivism",
 "Kuhn's book marks a break with the positivist picture of what research should look like. What does that picture demand?",
 [("The belief that science always produces socially positive outcomes.",
   "A false friend. Positive here has nothing to do with good."),
  ("A view emerging in the Enlightenment: non-contextual, formal and standardised research that seeks analytically to separate distinct variables.",
   "Positive here names the doctrine that real knowledge comes only from what you can observe and measure, which is called <b>positivism</b>. And the whole shared kit a field works inside, meaning its theories, its instruments, its values and its assumptions about what exists, is what Kuhn calls a <b>paradigm</b>. Now take her three words one at a time. Non-contextual: where and when you did the work should not matter. Formal and standardised: anyone following the procedure gets the same result. Separating variables: isolate one thing and hold the rest still. Kuhn's paradigms attack the first of these directly, because a paradigm is a context."),
  ("The claim that only sense experience counts as evidence, originating with Bacon.",
   "The view that knowledge starts in the senses, which is called <b>empiricism</b>, is the root positivism grew from. It is not the description she gave."),
  ("The doctrine that every scientific claim must be falsifiable.",
   "Popper, who was arguing against the positivists.")],
 2, "Positive here is about a kind of method, and the first of its three features is the one Kuhn destroys."),

("Kuhn &middot; where his influence is strongest",
 "Where is Kuhn's influence strongest?",
 [("In physics.",
   "His training was in physics and his effect there was slight."),
  ("In sociology.",
   "Real influence. She named a different field."),
  ("In the history of science.",
   "Which makes sense, because his argument is a claim about how to write history. If you cannot explain a sequence by what it led to, the historian's job changes: you have to reconstruct what the old paradigm looked like from inside, as a working system."),
  ("In analytic philosophy.",
   "His reception there was largely hostile.")],
 3, "His central methodological objection is to a way of writing about the past."),

("Kuhn &middot; Copernicus",
 "Copernicus moved the sun to the centre of the system. What was his reason for doing it?",
 [("That the earth rotates on its axis once a day.",
   "True of Copernicus and not the framing she chose."),
  ("That observation should outrank authority.",
   "A Baconian slogan, and the Copernican system was not driven by new observations."),
  ("That the sun needed to be at the centre for circular motion to work.",
   "She called this the important framing, so it is likely to be the asked one. Note what it means: he was not following better data. He was preserving perfect circles, an old commitment inherited from the Greeks. A revolution launched in order to keep something old."),
  ("That the planets move in ellipses.",
   "Kepler, sixty years later. His ellipses finally broke the circles Copernicus was protecting.")],
 3, "She flagged one of these as her framing and as the important one. It gives his motive. The conclusion is the familiar part."),

("Kuhn &middot; what Copernicus opposed",
 "Copernicus held the sun stationary and the earth moving. Whose worldview was he arguing against?",
 [("Plato's, with the Forms in a realm outside ours.",
   "Plato's theory of Forms is not an astronomy."),
  ("Aristotle's earth-centred worldview.",
   "Which is why the Greek picture had to break before modern science could start, and why Aristotle keeps reappearing as the thing being overthrown. Bacon attacks his method, Copernicus attacks his cosmos."),
  ("Bacon's empiricism.",
   "Bacon is born eighteen years after Copernicus dies."),
  ("The Church's, which had no position on astronomy.",
   "The Church's astronomy was Aristotle's, so this misses the source.")],
 2, "The same figure whose method Bacon attacks about eighty years later."),

("Kuhn &middot; the Scientific Revolution",
 "What did the Scientific Revolution of the sixteenth and seventeenth centuries replace, and with what consequence for philosophy?",
 [("It replaced the Greek worldview that had prevailed for two thousand years, and science becomes its own discipline, distinct from philosophy.",
   "The consequence is the one the whole course is about. Before this, studying nature was natural philosophy, a branch of philosophy. It also replaced the Christian focus of the European worldview and embraced utilitarian concerns, meaning knowledge valued for what it can do."),
  ("It replaced medieval alchemy, and philosophy absorbed science into itself.",
   "The direction of the split is the reverse."),
  ("It replaced religion with reason, and philosophy was abolished in the universities.",
   "Neither half happened."),
  ("It replaced Latin with vernacular languages, and philosophy became accessible.",
   "A real change of the period. Her point is different.")],
 1, "Ask what the people doing it were called before and after."),

("Kuhn &middot; foundationalism",
 "What is foundationalism, and what is the problem with it?",
 [("The view that science rests on experiment, and the problem is cost.",
   "Not her definition and not her problem."),
  ("The idea that knowledge can be traced back to a firm foundation we keep building on, and the problem is induction.",
   "Foundationalism concerns what holds a claim up right now. History is a separate question. Take a real chain. You say this kettle will boil at 100 degrees. Why? Because water boils at 100 at sea level. Why believe that? Because every measurement anyone has ever made came out that way. Why does that settle it? <b>Here the chain is meant to stop.</b> A measurement is treated as something that needs no further reason behind it, and that bottom layer is the foundation. Every claim above it rests on a claim below, and the bottom one rests on nothing further. Her phrase <i>traced back</i> means traced downward along that chain of reasons. It does not mean traced backward through time, which is the separate idea in this same lecture called Whig history. The problem she named: the step from <i>every measurement so far</i> to <i>water boils at 100</i> is <b>induction</b>, and no number of measurements makes a general law safe. So the one layer holding everything else up is the one layer nobody can secure."),
  ("The view that every field needs a founder, and the problem is credit.",
   "A pun on the word. The doctrine is something else."),
  ("The claim that mathematics underlies all science, and the problem is that biology resists it.",
   "Not discussed.")],
 2, "The metaphor is architectural, and the trouble is at the bottom."),

("Kuhn &middot; foundationalism against telos",
 "One other idea in this course resembles foundationalism and works in the opposite direction. Which, and what is the difference?",
 [("Not like Plato's Forms, because foundations are physical.",
   "Not the contrast she drew."),
  ("Not like Bacon's induction, because foundations are deductive.",
   "Induction is named as foundationalism's problem, so they are not opposites."),
  ("Not like the Aristotelian <i>telos</i>, because in <i>telos</i> a thing moves toward an ideal form, while a foundation is something you build up from.",
   "Two different pictures of direction. <i>Telos</i> pulls from in front: the end is already fixed and the thing grows toward it. A foundation pushes from below: nothing is fixed ahead and you stack upward. Worth holding, because Kuhn then rejects both as accounts of how science moves."),
  ("Not like Foucault's power-knowledge, because foundations are neutral.",
   "Not a contrast she drew.")],
 3, "One picture has the destination fixed in advance. The other has only a starting point."),

("Kuhn &middot; revolutions",
 "What happens in a Kuhnian revolution?",
 [("A theory is falsified by a crucial experiment.",
   "Popper's picture, and Kuhn's account makes the crucial experiment hard to believe in."),
  ("The disciplinary matrix is revised and an anomalous problem gets solved.",
   "A result a field cannot make fit, however hard it tries, is an <b>anomaly</b>, and <b>disciplinary matrix</b> is Kuhn's later and more careful word for a paradigm: the whole shared kit of theories, values, instruments and assumptions. Revision of the kit, plus the solving of the problem that would not go away. Both halves are needed."),
  ("A majority of scientists change their minds at once.",
   "Kuhn's account has the old generation largely not changing its mind at all."),
  ("A new instrument makes the old theory unnecessary.",
   "Her particle detector example argues the reverse: instruments often survive the revolution unchanged.")],
 2, "Two things happen, and one of them is to the shared equipment of the field."),

("Kuhn &middot; the critique",
 "What is the main critique of incommensurability, and how did Kuhn respond to it?",
 [("That paradigms do not really exist; Kuhn abandoned the term.",
   "He never abandoned it."),
  ("That semantic incommensurability can be overcome and so is not a real limitation; Kuhn modified his position and emphasised that communication remains difficult within the scientific community.",
   "<b>Incommensurability</b> is Kuhn's word for two paradigms having no shared measure to compare them by. <b>Semantic</b> means to do with meaning. The critics' point: if a term shifted meaning, a historian can learn the old meaning, so the barrier is a translation problem and translation problems get solved. Kuhn retreated from impossible to difficult, which is a real concession."),
  ("That revolutions are rarer than he claimed; Kuhn conceded and narrowed his examples.",
   "Not the critique she gave."),
  ("That the history was inaccurate; Kuhn revised the book.",
   "Not her account.")],
 2, "The critique attacks the first of his three reasons, the one about the meanings of terms."),

("Kuhn &middot; the particle detector",
 "Kuhn says two paradigms can have no shared measure to compare them by. Here is a counter-example: the same particle detectors were used in the same way before and after the theory around them changed. Why does that trouble his claim?",
 [("It shows revolutions happen far more often than Kuhn allowed.",
   "How often revolutions happen is a separate argument, and the detector says nothing about it."),
  ("It shows that a new instrument is what causes a revolution in the first place.",
   "The force of the example is that the instrument did not change at all. Nothing new arrived."),
  ("Something came through the change untouched and went on working the same way, so there is a shared measure after all, and the two paradigms can be compared through it.",
   "Incommensurability means there is no common yardstick. The detector is a common yardstick: both paradigms accept what it reads and both use it the same way. So at least one thing survived that either side can be held against, and the two are not sealed off from each other."),
  ("It shows that what an instrument reads depends on the theory behind it, so the same readings came to mean something different.",
   "That is the theory-ladenness of observation, and it is an argument <b>for</b> Kuhn. Her example was offered against him, so this one points the wrong way.")],
 3, "If both sides go on trusting the same detector, ask what that detector is to the two of them."),

("Kuhn &middot; her conclusion",
 "Kuhn denies that science has a single fixed method, a secure foundation, or steady progress toward truth. Something still has to explain why it works as well as it does. What answer does the course give?",
 [("Science is unified by the scientific method.",
   "The view the whole course is written against."),
  ("Science is an ad hoc system that is disunified, and it does not need one abiding thread or foundational idea to be successful. She attached the point to Wittgenstein.",
   "Ad hoc means put together for the particular case at hand. She attached this to Wittgenstein: a set of practices can be held together by overlapping family resemblances with no single feature running through all of them. Success without unity, which answers the course's title question directly."),
  ("Science is progressing toward a complete description of nature.",
   "Rejected under his view of progress."),
  ("Science is a social construction with no claim on truth.",
   "Stronger than anything she claimed, and week 4 is careful to avoid it.")],
 2, "Ask what holds a set of things together when no single feature runs through all of them."),

("Kuhn &middot; the modernity of science",
 "Indoctrination is Kuhn's second reason for incommensurability: scientists are trained into a paradigm and cannot step outside it. Which group does that leave best placed to break one, and what becomes of the other group?",
 [("New scientists are less indoctrinated with generalisations and more responsible for change, and older scientists tend to become more conservative and marginalised if they do not change.",
   "This is the same mechanism as Kuhn's second reason for incommensurability, seen from the other side. Indoctrination is what makes a paradigm hold, so the least indoctrinated are the ones who can leave it. She added that scientists attend mostly to recent findings and treat past research as low value, which makes the field look young and modern."),
  ("New scientists defend the paradigm hardest because their careers depend on it.",
   "A reasonable sociological guess, and the opposite of what she said."),
  ("Older scientists lead revolutions because only they have the standing to.",
   "The reverse of her claim."),
  ("Age makes no difference, because the paradigm constrains everyone equally.",
   "She drew an explicit contrast between the two groups.")],
 1, "Which group has had the least time to be trained into the paradigm?"),

("Kuhn &middot; why revolutions are not progress",
 "In normal science, each new result adds to a pile that keeps growing, so it is easy to see the field moving forward. Kuhn refuses to call a revolution progress. Why?",
 [("Because they are too rare to count as a trend.",
   "Frequency is not the issue."),
  ("Because they both build and destroy paradigms.",
   "Her exact reason, and the contrast with normal science is what makes it clear. Under normal science progress is easy to talk about, because achievements accumulate and are apparent. A revolution adds and subtracts at the same time, so there is no single direction to measure. Oxygen chemistry gained a great deal and lost every question phlogiston could answer."),
  ("Because they are driven by politics and funding.",
   "Not his argument."),
  ("Because the new paradigm is usually less accurate at first.",
   "Often historically true. She listed a different reason.")],
 2, "A revolution does two things at the same time, and the second of them is what stops it counting."),
]
