# Question bank, week 2. Every item comes from the professor's posted notes for
# 14 and 16 September, or from the lecture recording of 14 September.
# Shape: (topic, question, [(option, why) x4], answer index starting at 1, hint)

WEEK2 = [
('Schadewaldt &middot; where techne belongs',
 'Schadewaldt places <i>techne</i> between two other kinds of knowing. Which two, and what makes <i>techne</i> different from the higher one?',
 [('Between <i>doxa</i> and <i>dialektike</i>. <i>Techne</i> differs because it can be taught.',
   "<i>Doxa</i> is opinion and dialectic is Plato's method. Neither is in the quoted passage."),
  ('Between <i>empeiria</i>, mere experience or know-how, and <i>episteme</i>, theoretical knowledge.',
   '<i>Techne</i> differs because <i>episteme</i> concerns what is immutable and primary, while <i>techne</i> bears on what is mutable and in the process of becoming. The passage she quoted from page 29. <i>Techne</i> is productive knowledge, so it works on things that are still changing. So it ranks below <i>episteme</i> and above raw experience.'),
  ('Between <i>physis</i> and <i>telos</i>. <i>Techne</i> differs because it has no goal of its own.',
   '<i>Physis</i> and <i>telos</i> are not kinds of knowing.'),
  ('Between craft and art. <i>Techne</i> differs because it produces useful things.',
   'Both English words translate <i>techne</i> itself, so this is circular.')],
 2, 'One Greek word means plain experience. The other is the root of the English word <i>epistemology</i>.'),

('Schadewaldt &middot; atechnia',
 'What is <i>atechnia</i>?',
 [('The refusal to use technology at all.',
   'The word names a failure of knowledge. Nobody in it is refusing to act.'),
  ('Knowledge that is productive and rich, but which has a false idea of the thing itself: a blunder.',
   'Her gloss on the slide was that <i>atechnia</i> is a false idea of the thing, held confidently. Note that it can be rich and diverse and still be a blunder, which is the uncomfortable part.'),
  ('The loss of a craft when nobody is left who can practise it.',
   'Not a claim in the lecture.'),
  ('Nature acting without human involvement.',
   'That is <i>physis</i>.')],
 2, 'The prefix <i>a</i> means without. What is it without, given the knowledge in question still works?'),

('The Greeks &middot; Heraclitus',
 "Heraclitus, sixth century BCE, wrote that sound thinking is man's greatest power, and that his highest aptitude is being able to say what is and &ldquo;fashion creatively by hearkening to nature&rdquo;. What does that assume about nature?",
 [('Nature is in harmony.',
   'Her summary line, written under the quotation. It matters because both Plato and Aristotle accept it and then split over what follows. All three agree there is an order out there. Heraclitus says you reach it by listening to nature. <b>Plato keeps the order and throws out the method</b>: the senses show you shadows, the real order is the Forms in a realm outside this one, and you get there by dialectic. <b>Aristotle keeps both</b>: the order is in the things around you, as form and an end they grow toward, so looking at the world is exactly how you find it. That is the disagreement the whole of week 2 is about, and the thing nobody disputes is that there is an order at all.'),
  ('Everything is in flux.',
   'The famous Heraclitus line about stepping into the same river twice. She used a different one.'),
  ('Man is the measure of all things.',
   'Protagoras.'),
  ('The unexamined life is not worth living.',
   'Socrates, in the <i>Apology</i>.')],
 1, 'Hearkening means listening. What does the quotation assume is out there to be listened to?'),

('Plato &middot; who is speaking',
 "What has to be kept in mind when reading any line out of one of Plato's dialogues?",
 [('Socrates wrote nothing, so the dialogues are our only record of his real views.',
   "The opposite of her point. She said Socrates was a real person, and this is Plato's Socrates."),
  ("Plato does not speak in his own texts. Socrates was a real person, but the Socrates in the dialogues is Plato's.",
   "Which means you can never quote a line as Plato's own opinion. It is a character's. She ran the Academy point alongside it: twenty-six dialogues, and a school."),
  ('The dialogues were written down by students from memory.',
   'Not claimed anywhere in the lecture.'),
  ('Each dialogue is set in a different city, so the arguments are local.',
   'Not a claim she made.')],
 2, 'Count how many times Plato uses the word <i>I</i> in the <i>Republic</i>.'),

('Plato &middot; dialectic',
 'What is dialectic, in Plato?',
 [('A debate in which two speakers argue opposite sides to entertain an audience.',
   'That is closer to the sophists, whom Plato is attacking.'),
  ('The Platonic method of inquiry, the best way to get to the truth, and the process of separating opinion from knowledge and understanding.',
   "Her definition. It is a method, which is why it belongs in a course on scientific method: Plato's answer to the question of how you find out anything at all. The cave is the picture of it, and dialectic is the procedure."),
  ('The historical process by which one idea gives rise to its opposite.',
   'Hegel and Marx, and about two thousand years later.'),
  ('The ranking of the crafts below theoretical knowledge.',
   'A conclusion Plato reaches. The question asks for the method he reaches it by.')],
 2, 'Two of these four are real meanings of the word from other centuries. Which one is the one she defined?'),

('Plato &middot; philosopher kings',
 'Why should philosophers rule, and what does their education require?',
 [('Because they are the only ones who want power, and their education requires rhetoric and law.',
   "Plato's point is close to the reverse: the people fit to rule are the ones not hungry for it."),
  ('Because they are awake while everyone else is dreaming, and their education needs geometry and astronomy.',
   'Her quotation described them exactly that way. The geometry and astronomy matter: for Plato mathematics is a way to gain access to the abstract, which is the contrast she later drew with Bacon, for whom mathematics predicts what physical bodies will do.'),
  ('Because they are the wealthiest class and can afford to govern without payment.',
   'Not a claim in the lecture.'),
  ('Because they have left the cave and will not return to it.',
   'In the allegory the one who has left is made to go back down.')],
 2, 'The subjects are the two that deal in things you cannot touch.'),

('Metaphysics &middot; where the word comes from',
 'Where does the word metaphysics come from, and what does the field ask?',
 [('From the Greek for beyond nature, because the subject deals with what is supernatural.',
   'The popular explanation, and she gave the other one. The supernatural never comes into it.'),
  ("From the title of Aristotle's book, which compilers placed after his <i>Physics</i> in the order of the works.",
   "The field asks what the origin and nature of all things in the cosmos are, and how we investigate them. A filing decision became the name of a discipline. Worth having, because it is a small concrete case of the course thesis: a category in science got its name from a filing accident. The subject's own nature had nothing to do with it."),
  ("From Plato's Academy, where it named the final year of study.",
   'Not claimed anywhere.'),
  ('From the Latin for the study of first causes, coined in the Middle Ages.',
   'The word is Greek and predates the Middle Ages.')],
 2, '<i>Meta</i> here means after. After what, and in what sense of after?'),

('Which theory matches which philosopher',
 "In Bacon's simile, the ant, the spider and the bee stand for three ways of working. Who is the spider?",
 [('The alchemists, who only store things up and use them.',
   'That is the ant. Bacon calls them the empirics: they collect, and nothing happens to what they collect.'),
  ('The proper natural philosopher, who gathers material and then digests it.',
   'That is the bee, and it is the one Bacon wants you to be.'),
  ('The Aristotelians, who spin webs out of their own entrails.',
   "The dogmatists, in Bacon's word. The insult is precise: they produce elaborate systems out of themselves and take nothing in from the world. Ant collects and does not think, spider thinks and does not collect, bee does both. From <i>Novum Organum</i> I.95, quoted in full on her slide."),
  ('The Greeks, who let ethics and politics dominate philosophy.',
   'A real Bacon complaint, and a separate one.')],
 3, "Where does a spider's web physically come from?"),

('Bacon &middot; his complaint about the ancients',
 'What did Bacon say had gone wrong with philosophy in Greece and Rome?',
 [('Ethics and politics dominated philosophy, with the consequence that natural philosophy performed the role of a servant.',
   'Her wording. The charge is about rank: studying nature was treated as a junior subject that served the questions people really cared about. Bacon wants it at the centre, because it is the part that produces power over the physical world.'),
  ('They had no mathematics capable of describing motion.',
   'Not his complaint, and the Greeks had a great deal of mathematics.'),
  ("They wrote in dialogue form, which hides the author's own view.",
   'A fair observation about Plato and not a Bacon complaint.'),
  ('They relied on experiment without any theory to guide it.',
   'That is his charge against the alchemists, the ants.')],
 1, 'He is making a claim about which subject was treated as more important than which.'),

('The Middle Ages &middot; Deism',
 'Around 1300 the first ideas of Deism start to develop. What is the picture, and why does it matter for science?',
 [('God as a clockmaker who set the world in motion, which makes studying the mechanism a pious act.',
   'Once God winds the world up and steps back, the world is a mechanism, and taking it apart to see how it runs becomes a way of admiring the maker. That is how a religious worldview ends up licensing mechanical science.'),
  ('God as a judge who intervenes constantly, which makes natural law impossible.',
   'This is the view Deism moves away from.'),
  ('The denial that God exists, which frees science from the Church.',
   'Deism is not atheism. There is a maker in the picture.'),
  ('The claim that the world is eternal and had no beginning.',
   'That is closer to Aristotle, and it is what Christian thought rejected.')],
 1, 'The usual image for it is a piece of machinery that keeps running after you wind it.'),

('Plato &middot; the shape of the journey',
 'Leaving the cave means moving upward, out of one realm and into another. What are the two realms, and what is the climb?',
 [('Out of the sensible world, where the shadows are, and up into the intelligible realm.',
   'Plato calls the climb the journey of the soul. Sensible means what the senses reach: what you can see, hear and touch. Intelligible means what only thought reaches. The cave floor is the first and the sunlight is the second. Calling it a journey of the soul tells you the change is in the person and not in the scenery, which is why education is a turning around and not a delivery of facts.'),
  ('Out of the private world of opinion and into the shared world of agreement.',
   'Agreement is not his test. A whole cave agreeing about the shadows would still be wrong.'),
  ('Out of the city and into the countryside, where there are fewer distractions.',
   'No geography is involved.'),
  ('Out of childhood and into adulthood.',
   'Age does nothing in the allegory. A grown prisoner is as chained as a young one.')],
 1, 'One realm is reached by the senses and one only by thought.'),

('Plato &middot; what it feels like',
 'The freed prisoner is turned around, stood up and made to walk toward the light. What does the text say about the experience?',
 [('It is immediately liberating.',
   'If it were pleasant, nobody would need to be made to do it.'),
  ('It is painful, and the prisoner has to be compelled.',
   'Learning as painful. This is the reason education needs a city built around it: left alone, nobody chooses the climb. It also explains the ending, since a person who found the ascent agonising has to be sent back down, and the ones below have no reason to believe him.'),
  ('It is impossible without a teacher present at every stage.',
   'A guide appears in the story and the pain is the detail the text dwells on.'),
  ('It makes no difference to the prisoner, who sees the same things either way.',
   'He is dazzled and cannot see properly at first, which is the opposite of no difference.')],
 2, 'Ask why anybody would have to be compelled to do something good for them.'),

('Plato &middot; what the cave is for',
 'The allegory of the cave is usually read as a story about reality. What questions is it actually built to answer?',
 [('How a city should be governed and by whom.',
   'That follows later from the answer, and it is not what the allegory itself is working on.'),
  ('How we know what is true, how we check a fact, how we know where our information came from, and what methods of inquiry to use.',
   'Which makes it a text about method, and that is why it opens a course on scientific method. The shadows are a picture of taking the readily available evidence for the thing itself. Everything after it in this course is another answer to the same four questions.'),
  ('Whether the gods exist and what they are like.',
   'No theology in the allegory.'),
  ('Why people disagree about politics.',
   'Not the subject.')],
 2, 'Ask what the allegory would be doing in a course about scientific method.'),

('Plato &middot; the Academy',
 'Plato ran a school in Athens. What was it, and what is notable about who attended?',
 [('The Lyceum, and only Athenian citizens could enrol.',
   "The Lyceum is Aristotle's school, founded later."),
  ('The Academy, and aristocratic women are known to have attended it.',
   'Worth holding for two reasons. It is where the word academy comes from. And the presence of women there is a useful fact to have when weeks 4 and 5 argue that science has been a closed shop, because the closure is not a fixed feature of intellectual life.'),
  ('The Stoa, open to anyone who turned up.',
   'The Stoa is where the Stoics taught, two generations later.'),
  ('A private tutoring arrangement with no fixed premises.',
   'It was a school with a site and a name.')],
 2, 'The English word for a scholarly institution comes from its name.'),

('Schadewaldt &middot; sorting the examples',
 'A river, an oak tree, a bronze statue and a ship. Which belong to <i>physis</i> and which to <i>techne</i>?',
 [('All four are <i>physis</i>, because the materials are all natural.',
   'The materials are, and the statue and the ship are not: somebody had to make them what they are.'),
  ('The river and the oak are <i>physis</i>; the statue and the ship are <i>techne</i>.',
   "The test is whether the thing grew out of its own source or whether a person made it be what it is. The oak contains what makes it an oak. A ship is bronze and timber arranged by somebody, so it is a combination of man and nature. Schadewaldt's complaint is that modern thought treats the two as different in kind, where the Greeks saw the second as continuous with the first."),
  ('The river and the ship are <i>physis</i>; the oak and the statue are <i>techne</i>.',
   'A ship does not build itself and an oak needs nobody.'),
  ('All four are <i>techne</i>, because a person has to name them before they count as anything.',
   'Naming is not the test, and that claim belongs to week 4.')],
 2, 'Ask of each one whether it would be what it is with no person involved.'),

('Aristotle &middot; what follows from where he puts form',
 "Aristotle keeps form inside the object. What does that let him do that Plato's theory does not?",
 [('Prove the existence of God from first principles.',
   'Not the consequence drawn in the lecture.'),
  ('Study actual animals and plants, cut them open, and learn something about what a thing is by examining it.',
   'He is called the first biologist for exactly this reason. If what makes a dog a dog is in the dog, then the dog is worth examining. If it is in a realm outside this one, examining dogs tells you about copies, and Plato sends his students to mathematics instead.'),
  ('Reject the senses as a source of knowledge.',
   'That is closer to Plato, who treats the senses as shadows.'),
  ('Explain why the planets move in circles.',
   'A later question. The location of form buys him something else.')],
 2, 'If the thing that makes a dog a dog is inside the dog, what is now worth doing to dogs?'),

('Aristotle &middot; what explaining consists of',
 'If every thing has a <i>telos</i>, an end it grows toward, what does it take to explain something?',
 [('Saying what it is made of.',
   'Material is one part of an Aristotelian account. It cannot be the whole of it, because the same bronze makes a statue or a bell.'),
  ('Saying what it is for, which means naming the end it is heading toward.',
   'Explanation by purpose. An acorn is explained by oak. This is the habit Bacon attacks: if a thing already carries its own purpose, the knower waits to receive it. And it is the one Kuhn rules out of history, because an event cannot be explained by what it later turned into.'),
  ('Finding the law that governs its behaviour.',
   'Explanation by law arrives with the new science of the 1600s.'),
  ('Showing which Form it is a copy of.',
   "That is Plato's kind of explanation.")],
 2, 'Picture explaining an acorn to somebody who has never seen one.'),

('Schadewaldt &middot; the accounting',
 'Schadewaldt sets out what reducing nature to what is calculable has bought, and what it has cost. What are the two sides?',
 [('It bought nothing, and cost the Greek sense of nature.',
   'He is far more generous than that, and the generosity is what makes the complaint land.'),
  ('It bought the most astounding discoveries and the greatest means of power, and it cost an impoverishment that is hard to estimate.',
   "Both halves are his. He will not argue that the method fails, because it plainly works. His claim is that something was dropped on the way and nobody can price it. An argument that concedes the opposition's best evidence first is much harder to dismiss."),
  ('It bought prediction, and cost nothing worth having.',
   'The second half is the reverse of his position.'),
  ('It bought moral progress, and cost religious belief.',
   'Neither item is in his accounting.')],
 2, 'He praises the results in the same breath as the complaint, and the praise is not faint.'),

('Schadewaldt &middot; which pairs came apart',
 'The dualism Schadewaldt describes split several pairs of things that the Greeks had held together. Which pairs?',
 [('Mind and body, reason and emotion, male and female.',
   'Real splits in the history of philosophy and not the ones he lists.'),
  ('Thought and extension, nature and spirit, nature and freedom, subject and object.',
   'Four pairs, and the last one is the one that matters most for this course. Once the observer counts as subject and the world as object, the person doing the looking stands outside what is looked at, and his fix is to put them back in. Weeks 5 and 6 make the same move under the name standpoint theory.'),
  ('Theory and practice, pure and applied, science and engineering.',
   'A modern set of distinctions and not his.'),
  ('Fact and value, is and ought.',
   'A real split, named by Hume. His list is a different one.')],
 2, 'One of the four pairs names the observer and the thing observed.'),

('Rousseau &middot; what follows from virtue',
 'Rousseau writes that barbarous people are those who lack virtue. Given that he also says progress comes only through education, what does the pair commit him to?',
 [('That a society is judged by its technology, since technology is what education produces.',
   'He is sceptical about exactly that measure.'),
  ('That education has to produce virtue, so a society with great learning and no virtue counts as barbarous however advanced it is.',
   'Which is why he can be inside the Enlightenment and against its favourite claim. Progress in the sciences and arts is not progress at all unless the people come out better. He points back to Plato, Socrates and Aristotle because they tied education to character.'),
  ('That barbarians cannot be educated.',
   'The reverse: education is his remedy.'),
  ('That virtue is innate and education is wasted.',
   'He makes education the only route to progress.')],
 2, 'Put the two claims together and ask what an advanced society with no virtue would count as.'),

('The era question &middot; the Greeks',
 'Put these four in order, earliest first: Aristotle, Heraclitus, Homer, Plato.',
 [('Homer, Heraclitus, Plato, Aristotle',
   'Homer eighth century BCE, Heraclitus sixth, Plato 428 to 348, Aristotle 384 to 322. The two philosophers overlap by about thirty years, since Aristotle studied under Plato. The detail standard here is centuries: Homer is first, Heraclitus is two hundred years later, and the other two are a pair at the end.'),
  ('Heraclitus, Homer, Plato, Aristotle',
   'Homer is two centuries before Heraclitus.'),
  ('Homer, Heraclitus, Aristotle, Plato',
   "Aristotle was Plato's student, so Plato comes first."),
  ('Homer, Plato, Heraclitus, Aristotle',
   'Heraclitus is sixth century BCE, well before Plato.')],
 1, 'Two of the four overlap in time, and one taught the other.'),
]
