# Question bank, week 4. From the professor's posted notes for 28 and 30 September
# (Sismondo ch. 4 on stratification and discrimination, ch. 6 on social construction)
# and from Kevin's notes on the 30 September class.

WEEK4 = [
('Stratification &middot; do citations show influence',
 'Of the 55 Nobel laureates working in the United States in 1963, how many had studied or collaborated with a previous prize-winner, and what difference did it make to them?',
 [('About a third, and they won at roughly the same age as everyone else.',
   'Both halves understate what the numbers show.'),
  ('34 of the 55, and those who had worked with a laureate before doing their own important research won at an average age of 44, against 53 for the others.',
   'Zuckerman 1977, quoted on her slide. Her conclusion from it: scientists tend to form elite groupings. The nine-year gap is the part to carry, because it is a measurable career advantage attached to who you trained with and not to what you found.'),
  ('All 55, because the prize is only ever awarded inside established schools.',
   'The figure is 34, and the remaining 21 matter to the argument.'),
  ('12 of the 55, which she offered as evidence that mentorship has little effect.',
   'Her reading of the numbers runs the other way.')],
 2, 'Her conclusion from the figure was that scientists form elite groupings. Which option supports that?'),

('Stratification &middot; what Bacon expected',
 "What did Francis Bacon expect the inductive method to do to the differences between people's intellectual abilities, and how did it turn out?",
 [('He expected it to level the differences amongst intellectual abilities.',
   "In practice a small number of scientists dominate: 10 per cent of authors produce half of all papers, and 80 per cent of citations go to 20 per cent of papers. Bacon's method works by piling up particular cases and reasoning upward to a general law, which is called <b>induction</b>. This is why he is in this lecture. His promise was that a method anyone can follow makes genius unnecessary, so ordinary people working carefully would do the work. The distribution of output says something else happened."),
  ('He expected science to be the preserve of a gifted few, which is what occurred.',
   'The opposite of his claim. His whole pitch was that method replaces genius.'),
  ('He expected it to make science profitable, which it did.',
   'Not the claim in these notes.'),
  ('He expected it to end disagreement between schools, and it did not.',
   'Not the expectation she quoted.')],
 1, "Bacon's pitch was that a method anyone can follow makes a certain kind of person unnecessary. Which kind?"),

('Stratification &middot; Cole and Cole on funding',
 'What did Cole and Cole find about how scientific funding is distributed?',
 [('It goes mostly to early-career researchers, to give them a start.',
   'The pattern described runs the other way.'),
  ('It is allocated by lottery among qualified applicants.',
   'Not described anywhere in the lecture.'),
  ('It is often placed in the hands of the most influential, or of institutions with a history of success and public trust built largely by having been around a long time.',
   'Note the phrase about being around a long time. It means part of what buys the funding is age, and age is not a measure of present quality. Funding opportunities then contribute to stratification, which is the layering of a field into a small advantaged group and everyone else.'),
  ('It follows citation counts directly, which makes it a fair measure of merit.',
   'She made the point that citations are not the only measure of success.')],
 3, 'The phrase in her notes about why some institutions are trusted is about duration.'),

('Stratification &middot; what a productive scientist looks like',
 'A recent study gave a list of behavioural categories for productive scientists, in order of importance. What was first on it?',
 [('Intelligent, then hard-working, then lucky.',
   'Not the list, and smart appears second in the real one.'),
  ('Persistent, then smart, then civil.',
   'Hermanowicz 2006. Persistence outranking intelligence is the point, and civil at number three is the surprise. The rest of the order runs creative, entrepreneurial, aggressive, tasteful, confident, adaptable.'),
  ('Creative, then confident, then adaptable.',
   'All three are on the list, lower down.'),
  ('Ambitious, then well-connected, then well-funded.',
   "Not the study's categories.")],
 2, 'The first item has nothing to do with ability, and the third is about manners.'),

('Stratification &middot; age and output',
 'Scientific output peaks at one age and falls afterwards. What age, and what explains the fall?',
 [('In their late twenties, and the decline is explained by family responsibilities.',
   'Neither the age nor the explanation given.'),
  ('In their mid-forties, after which it decreases, and the reason for the decline is unclear.',
   'That admission is the thing to remember. She said the reason is unclear, which means a question on this wants the fact and not an explanation. Note how oddly it reads beside the laureates who won at 44.'),
  ('Output is flat across a career.',
   'She described a peak and a decline.'),
  ('In their sixties, once they have institutional backing.',
   'Not the pattern given.')],
 2, 'She named an age and then declined to explain the decline.'),

('Stratification &middot; prestige',
 'Institutional prestige predicts productivity. What explains the link?',
 [('Prestigious places hire better people, so the prestige is just a result.',
   'The candidates are described as highly competitive with very slight distinctions between them, which undercuts this.'),
  ('Prestige has no causal effect and the correlation is accidental.',
   'She offered several mechanisms, so she takes the effect to be real.'),
  ('Better facilities and networking, more intellectual stimulation, greater internal pressure and reward, and more visibility and therefore more reward.',
   "If that is right, prestige by itself makes people's research valuable. Read the last sentence slowly, because it is the uncomfortable one. The same work done in two places is worth different amounts, and the difference comes from the place. That is cumulative advantage with a mechanism attached."),
  ('Prestigious institutions have more money, which is the whole explanation.',
   'Funding is one of several mechanisms she listed.')],
 3, 'One of these options ends with a claim that the place, by itself, changes what the work is worth.'),

('Stratification &middot; cumulative advantage',
 'What is the cumulative advantage hypothesis, and what does it do to the picture of science as a meritocracy?',
 [('Success breeds success, which makes scientific success look elitist and idiosyncratic where it had looked merit based.',
   'A system where who gets ahead tracks how good they are is called a <b>meritocracy</b>, and this hypothesis is what puts that description of science in doubt. The loop in concrete terms: a good first post means a bigger lab, a bigger lab means more results, more results means a stronger grant, a stronger grant means a bigger lab again. Nobody in the loop is doing anything unfair, and the gap widens anyway. This is the week 4 idea most likely to carry a question.'),
  ('Advantages accumulate across a lifetime but even out between generations.',
   'No such evening out is claimed.'),
  ('Scientists who publish early are penalised later.',
   'The reverse of the hypothesis.'),
  ('Merit accumulates, so the most successful are genuinely the most able.',
   'The hypothesis is offered as a challenge to exactly this reading.')],
 1, 'Four words, and the second two are the same as the first two.'),

('Discrimination &middot; Rossiter',
 "Margaret Rossiter's historical study of women in American science found a link between who works in a field and how the field is regarded. What is it?",
 [('Fields with more women attract more funding.',
   'The opposite direction.'),
  ('Feminisation is linked to a lowering of status and masculinisation to an increase of status, and women were pushed into the invisible sciences such as home economics and nutritional science.',
   'The 1982 finding underneath it is the sharp one: men perceive their own work as less masculine because women are present. So the status of the work tracks who is doing it. The work itself has not changed. Her examples of fields that feminised: sociology, economics, biology, chemistry.'),
  ('Women and men were paid equally once anti-discrimination law arrived in the 1960s.',
   'Not a claim in the lecture.'),
  ('Status is set by the difficulty of the subject, so the hard sciences stayed male.',
   'This is the justification the finding undermines.')],
 2, "The study is about what happens to a field's reputation when the people in it change."),

('Discrimination &middot; the golden age',
 'American science expanded fast after the Second World War, and the period is remembered as a golden age. What happened to women inside it, and what caused it?',
 [('It was a golden age for everyone, since funding expanded for all.',
   'The phrase she used was deliberately two-sided.'),
  ('It was a dark age for women, because more men were hired into the institutions where women had been working during the war.',
   'Two things at once: the field expands and a group inside it loses ground, because the expansion was staffed by men returning from the war. The 1960s anti-discrimination laws arose in response to the discrimination of the 1940s and 1950s.'),
  ("It ended women's exclusion from laboratory science.",
   'The reverse of what she described.'),
  ('It had no effect on the gender composition of science.',
   'She described a direct effect.')],
 2, 'The phrase pairs a golden age for one group with its opposite for another.'),

('Discrimination &middot; the pipeline',
 'Women in science and engineering are described through an image of a pipe. What is the image, and what does it imply about where the problem lies?',
 [('A ladder with missing rungs, so the problem is at the top.',
   'Not the image quoted.'),
  ('A pipe with leaks at every joint along its span, starting with a high-pressure surge of young women and ending with a trickle at the spigot.',
   'So there is no single point of failure. Every joint leaks, which is why no one fix repairs it. Her three-part summary was getting in, staying in, getting on, and she added that the intake matters too: women have to get into the pipe in the first place.'),
  ('A funnel, so the problem is that too few women apply.',
   'Intake is one part of her point, and the quotation is about losses all the way along.'),
  ('A closed valve at the end, so the problem is promotion to senior roles.',
   'Senior roles are where the trickle shows, and the losses happen throughout.')],
 2, 'The quotation names a leak at every joint, which rules out any single-cause answer.'),

('Discrimination &middot; Wenneras and Wold',
 'Peer review scores for postdoctoral fellowships at the Swedish Medical Research Council were studied in 2001. What did it take for a woman to be scored as competent as a man?',
 [('A recommendation from a senior male colleague.',
   'Not what the study measured.'),
  ('Roughly three extra papers in <i>Nature</i> or <i>Science</i>, or about 20 extra papers in an excellent specialist journal.',
   'The number is the thing to carry, because it converts a vague claim about bias into a measured quantity. Note what makes it powerful: peer review is the mechanism science uses to be fair, so the bias is inside the correction itself.'),
  ('A doctorate from a more prestigious institution.',
   'Not the finding.'),
  ('Nothing. The study found scores were equal.',
   "The study found men's accomplishments rated as overwhelmingly more valuable than apparently equivalent ones by women.")],
 2, 'The finding is a number, and the number is what makes it quotable.'),

('Discrimination &middot; how it works in practice',
 'How are young female scientists discriminated against in practice, and why do small differences matter?',
 [('Through open refusal of appointments, which is rare and so has little effect.',
   'She described something that works without anyone refusing anything.'),
  ('Smaller labs, worse startup conditions such as lower grants or salary and more teaching in place of research, and exclusion from informal networks.',
   'Where competition is strong, cumulative advantage turns small irritants into enough to keep women from getting on. Cole and Singer 1991. The mechanism is the one from the first half of the lecture, applied: each difference looks trivial and is shrugged off, and because advantage compounds, trivial differences at the start produce large gaps later. The doctoral student quoted on the slide gives the network version: nobody ever thought to ask her a technical question.'),
  ('Through formal quotas that cap the number of women hired.',
   'No such quotas are described.'),
  ('Through explicitly hostile supervisors.',
   'Her examples are structural and not about individual hostility.')],
 2, 'The answer has to connect to cumulative advantage from the first half of the lecture.'),

('Discrimination &middot; the maths gene',
 "Claims have been made about an inborn tendency, a biological <b>propensity</b>, explaining boys' better results in mathematics, and Harvard's president invoked biology in 2005. What is wrong with that kind of claim?",
 [('The claims are correct and explain most of the gap.',
   'The lecture rejects them.'),
  ('The claims are untestable and so neither true nor false.',
   'She gave a reason they fail, which is stronger than calling them untestable.'),
  ('Genes only ever act in environments, so such claims are ideological statements.',
   "They also run against recent trends, where boys' and girls' mathematics scores are converging. A claim that states a political position while dressed as a finding is what she means by an <b>ideological statement</b>. Two separate objections here and it is worth holding both. The first is conceptual: there is no such thing as a genetic effect outside an environment, so a claim about genes alone is a claim about nothing. The second is empirical: the gap has been shrinking, and genes do not change in thirty years."),
  ('The claims are irrelevant because women outperform men in science overall.',
   'Not a claim she made.')],
 3, 'She gave one objection about what a gene can mean and one about what the test scores have been doing.'),

('Discrimination &middot; the conclusion',
 'The week ran two halves, stratification and then discrimination. What single picture of science do the two halves add up to?',
 [('There is one principal cause, which is hiring.',
   'She said directly that there is no one reason.'),
  ('There is no one reason that keeps women out of science.',
   "Science looks much more like a boys' club than a meritocracy, and those in elite positions produce more because of a combination of competitive advantages. Notice that the conclusion of the second half is the conclusion of the first half with gender added. Cumulative advantage explains elite productivity in general, and discrimination is one more thing that compounds."),
  ('The problem has been solved by anti-discrimination law.',
   'Her 2005 and 2006 figures are given to show it has not.'),
  ('Women leave science by choice, so the distribution reflects preference.',
   'The argument is built against this reading.')],
 2, 'One half showed advantage compounding for everyone. The other showed who it compounds against.'),

('Social construction &middot; Hacking',
 'Ian Hacking wrote on constructivism in 1999. What is the core of constructivism, set against realism?',
 [('Scientific theories are made up and have nothing to do with the world.',
   'The overstatement. Nothing in the lecture denies that theories answer to the world.'),
  ('Any given theory is not the only one that could have been established, so the success of a theory is not by itself evidence for it.',
   'It could have been established another way. The claim is about what success proves. A working theory shows that this arrangement works. Whether some other arrangement would also have worked is left open. That is why a constructivist can accept every result of science and still refuse the inference from it works to it is the truth.'),
  ('Scientists construct their instruments, and therefore their results.',
   'Instruments appear in the lecture and this is not the Hacking claim.'),
  ('Only social facts are constructed; natural facts are discovered.',
   'The argument she presents applies to scientific facts too.')],
 2, "The claim concerns what a theory's working proves, and what it leaves open."),

('Social construction &middot; realism',
 'What is the realist position about scientific truth?',
 [('The view that one should accept a situation as it is and not try to change it.',
   'This is the everyday use of the word realism and it is a different thing entirely. Worth separating, because the two meanings share one word.'),
  ('The intuition that truths depend mostly on the natural world and only slightly on the people who articulate them: there is a way the world is, and it is possible to discover it and represent it accurately.',
   'Three parts: the world has a definite way it is, we can find it out, and we can represent it accurately. A constructivist can accept the first and still dispute the second and third.'),
  ('The view that only what can be measured is real.',
   'Closer to <b>positivism</b>, the doctrine that real knowledge comes only from what you can observe and measure.'),
  ('The view that scientific theories are useful fictions.',
   'That is the view that a theory is a useful tool, with no claim attached about what is really there, which is called <b>instrumentalism</b>. It is the opposite of realism.')],
 2, 'One of these is the ordinary English sense of the word and the trap in the question.'),

('Social construction &middot; the sociology of knowledge',
 'How does something become a real social institution, on the account given?',
 [('By being written into law.',
   'Law is one way and the account given is more general.'),
  ('Institutions exist because enough people act as if they exist, which means they cannot simply be wished away.',
   "Her example was polite society, or polite behaviour. The conditions listed: knowledge of a thing encourages behaviour that increases other people's tendency to act as though it exists, there is reasonably common knowledge of it, and that knowledge is transmitted. Politeness is a good test case, since there is no law requiring it and no building that houses it, and it still constrains everybody."),
  ('By being discovered to correspond to a natural fact.',
   'The account is explicitly about things that are not given by nature.'),
  ('By being agreed on in an explicit social contract.',
   'No agreement is required on this account, only behaviour.')],
 2, 'Her example was something with no law behind it that everyone still obeys.'),

('Social construction &middot; why gender counts as real',
 'Gender is argued to be real. On what grounds?',
 [('Because it is determined by biology.',
   'The passage says genders are undoubtedly not simply given by nature.'),
  ('Because it is recognised in law.',
   'Not the argument given.'),
  ('Because it is difficult not to take account of it.',
   'Gender structures create constraints and resources people have to reckon with, and treating people as gendered tends to create gendered people. Genders have causal powers, which is probably the best sign of reality we have. The test offered for reality is causal power: a thing is real if it makes a difference to what happens. The loop in the middle is the mechanism, since treating people as gendered produces gendered people, which then justifies the treatment. Historical research and differences between cultures show it is not simply given by nature.'),
  ('Because every known society has had it in the same form.',
   'The passage appeals to divergences between cultures, which is the opposite.')],
 3, 'The passage names one test for whether something is real, and it is about effects.'),

('Social construction &middot; contingently real',
 'Knowledge, methods, epistemologies, disciplinary boundaries and styles of work are called real social objects, and contingently real. What does contingently real mean?',
 [('They are real, and they did not have to be this way.',
   'They were built out of something and could have been built differently. A view about what counts as knowledge and how you are allowed to get it is an <b>epistemology</b>, and the list in the question is a list of things like that. <b>Contingent</b> means it could have been otherwise. The boundary between chemistry and physics is real, since it decides who gets hired into which department and whose paper gets reviewed by whom, and nothing in nature required the line to fall where it does.'),
  ('They are only real to the people who believe in them.',
   'Being real for some people and not others is a different claim, and these objects constrain everyone in the field.'),
  ('They are real only until they are disproved.',
   'Disciplinary boundaries are not the kind of thing that gets disproved.'),
  ('They are not really real, and the phrase is a hedge.',
   'The word real in the phrase is meant seriously, which is the point of it.')],
 1, 'Contingent is the opposite of necessary. Ask whether it had to be this way.'),

('Social construction &middot; the laboratory',
 'Karin Knorr Cetina wrote that nature is not to be found in the laboratory. What did she mean?',
 [('That laboratory results are fabricated.',
   'A charge of fraud. Her claim is different.'),
  ('That laboratories work on models and simulations, with nothing real involved.',
   'The materials in a laboratory are real. The point is what has been done to them.'),
  ('That to an outside observer the laboratory is a site of action from which nature is as much as possible excluded.',
   'It is a space of prepared materials, intentionally shaped and manipulated. Think of what is actually on a bench: purified reagents, bred strains, filtered air, controlled temperature. Every one of those is nature with most of nature removed. So a result from a laboratory is a result about a highly artificial arrangement, and getting it to apply outside takes extra work every time.'),
  ('That laboratories are too small to contain natural phenomena.',
   'Not an argument about scale.')],
 3, 'Picture what is physically on a laboratory bench, and ask how much of it you could find outdoors.'),

('Social construction &middot; how theories get built',
 'What is meant by saying scientific theories are constructed with reference to data but are not implied by the data?',
 [('The data are usually wrong, so theories go beyond them.',
   'The claim holds even when the data are perfect.'),
  ('A theory is built on real observations, and the observations alone do not determine which theory you should build.',
   "More than one theory fits the same fixed points. Kevin's own gloss in his notes says it plainly: a theory is based on real observations, and the observations alone do not automatically tell you exactly what theory to create. Her image was geometrical, making patterns appear given the fixed points that practice produces, the way more than one curve passes through the same scatter of dots."),
  ('Theories come first and data are gathered to support them.',
   'The order described runs from data to representation.'),
  ('Data are theory-laden, so there are no observations independent of theory.',
   'A real position in the field, and a different claim from the one made here.')],
 2, 'Picture a handful of dots on a page and ask how many curves pass through all of them.'),

('Social construction &middot; heterogeneous construction',
 "What is heterogeneous engineering, in Law's sense?",
 [('Engineering that combines several branches, such as mechanical and electrical.',
   'Heterogeneous here means mixing kinds of thing. Branches of engineering are a different sort of mixture.'),
  ('Building the artifact and building the environment in which it can function at the same time, by enrolling raw materials, skills, knowledge, capital and people who may not be immediately compatible.',
   'Neither half can usually be done on its own. The network is heterogeneous because it joins isolated parts of the material and the social world: equipment, established knowledge, patrons, money, institutions. And no single piece determines the shape of the whole, which is why a better device does not win by being better.'),
  ('Designing a technology to work in any environment without modification.',
   'The opposite of the claim, which is that the environment has to be built too.'),
  ('Combining several incompatible technologies into one product.',
   'Not the sense of the term.')],
 2, 'The word heterogeneous points at the mixture of material things and social things in one network.'),

('Social construction &middot; co-production',
 'Science and social order are said to be co-produced. What does that mean, and what was the example?',
 [('Science is produced by society, so social forces fully determine its content.',
   'A one-way claim, and co-production runs both ways.'),
  ('Scientific knowledge and social arrangements make each other.',
   'Good climate science depends on policies that fund it, and ideas of health and disease are defined by classifications of disease, so ADHD can be framed as a mental disorder or as extreme procrastination. Both directions at once. Researchers need funding to study climate change, so the policy produces the science, and the science is then used to justify the policy. The ADHD case shows the same loop in a classification: the category decides who counts as ill, and who counts as ill is then evidence that the category tracks something.'),
  ('Two laboratories producing the same result independently.',
   'Replication, and a different idea.'),
  ('Scientists and engineers collaborating on a shared product.',
   'Not the sense of co-production used here.')],
 2, 'The prefix co means the causation runs in both directions at once.'),

('The construction of kinds',
 'On the construction of kinds, what separates the nominalist from the realist?',
 [('The nominalist thinks classifications are useful; the realist thinks they are useless.',
   'Both sides think classification works. They disagree about why.'),
  ('The nominalist studies names and the realist studies things, so they are doing different jobs.',
   'They are answering one question, about whether the categories were found or made.'),
  ('The nominalist says kinds are human impositions, even where we share classifications easily, so the objects of classification are mental and linguistic.',
   "The realist says kinds are real features of the world. Kevin flagged this one as examinable while it was being taught. The nominalist's hard problem is that we agree on classifications so easily, which looks like evidence of tracking something real; the answer is that shared training explains the agreement. Behind it is Hacking: another theory could have been established, so success is not proof."),
  ('The nominalist denies that the external world exists.',
   'The overstatement. The claim is about our categories and leaves alone the question of whether there is anything out there.')],
 3, 'Both camps agree that classifying works. The disagreement is about what makes it work.'),

('Social construction &middot; the conclusion',
 "Chapter 6 spends its length arguing that laboratories shut nature out and that facts get built. Where, by the end of it, does science's power come from?",
 [('From the authority of its institutions.',
   'Institutions appear in the lecture and this is not her conclusion.'),
  ("From its ability to manipulate nature and measure nature's reactions, and to translate those measurements across time and space to other laboratories and other contexts.",
   'Laboratories and technology contribute to objectivity and objective knowledge. The second half is the one that answers the week. After a lecture arguing that laboratories exclude nature and that facts are constructed, she ends by saying those same laboratories produce objectivity. The construction claim describes how objective knowledge gets made. It leaves alone whether such knowledge exists.'),
  ('From the fact that its theories are true.',
   'The lecture spends its length arguing that truth is not what explains the power here.'),
  ('From public trust, which is why funding follows reputation.',
   'A point from the first half of the week. This conclusion is different.')],
 2, 'The answer gives laboratories a positive role, which is a surprise after an hour spent arguing they shut nature out.'),
]
