# Question bank, mixed set. The first batch, built straight from the eleven topics
# the professor named in her exam review on the last page of Kevin's notes.

MIXED = [
('Plato &middot; the text, the author, the dialogue',
 'The allegory of the cave comes from which text, and who are the two speakers in it?',
 [('The <i>Apology</i>, a conversation between Socrates and his accuser Meletus.',
   'The <i>Apology</i> is Socrates on trial. No cave in it.'),
  ('The <i>Republic</i>, a conversation between Glaucon and Socrates.',
   'Book seven of the <i>Republic</i>. Glaucon is the one being walked through the cave. Worth holding all three together, because she said there is a question about the text, the author and the name of the dialogue: Plato wrote it, the dialogue is the <i>Republic</i>, and Plato never speaks in his own name anywhere in it.'),
  ('The <i>Symposium</i>, a conversation between Socrates and Alcibiades.',
   'The <i>Symposium</i> is the drinking party about love.'),
  ('The <i>Timaeus</i>, a conversation between Socrates and Critias.',
   "The <i>Timaeus</i> is Plato's account of how the cosmos was made.")],
 2, 'Plato wrote twenty-six dialogues. This one is his long work about the ideal city.'),

('Plato &middot; what education is',
 'Plato writes that education is not "putting knowledge into souls that lack it, like putting sight into blind eyes". So what is it?',
 [('Filling the student with the knowledge the teacher already has.',
   'This is the exact thing the quoted line rejects.'),
  ('Training in a craft, until the hands know what to do without being told.',
   'That is skill at making or doing something, which the Greeks called <i>techne</i>, and Plato ranks it below the knowledge he is after here.'),
  ('Turning the soul around, so that it looks toward the light.',
   'Her phrase on the slide was "education is turning around". The eyes already work. They are pointed at the wall. Her line: sight is no good if you are not looking in the right place.'),
  ('Memorising the dialogues until the arguments can be reproduced.',
   'Nothing in the lecture supports this, and it is the opposite of a method of inquiry.')],
 3, 'If the eyes are not broken, what is the problem with them?'),

('Plato and Foucault &middot; why she put them side by side',
 'Beside Foucault\'s "panoptic utopia, the utopia of a perfectly governed city", the professor wrote on her own slide: "think Plato, <i>Republic</i>, the Kalliopolis". What is the Kalliopolis, and why is it there?',
 [('The cave itself, because both Plato and Foucault describe people who cannot see their own confinement.',
   'Tempting, and this is the one to beware of. The Kalliopolis is a city, and the cave is a separate image.'),
  ('The Athenian democracy Plato lived under, which Foucault treats as the first disciplinary society.',
   "Plato's Kalliopolis is his own invention, and he is against Athenian democracy."),
  ("Plato's ideal city, ruled by philosophers, where correct education is central, which is the same dream of a perfectly ordered city that Foucault finds in the plague town.",
   '<i>Kalli</i> means beautiful, so the most beautiful city. Her point in putting them together: Foucault says the plague town has a "political dream" of strict division and regulation reaching into the smallest details of everyday life, and that dream is old. Plato wrote the attractive version of it.'),
  ("Plato's name for the realm of the Forms, which Foucault treats as the model for the inspector's tower.",
   'The realm of the Forms is a transcendental realm, and it is not a city.')],
 3, '<i>Kalli</i> is the Greek for beautiful. <i>Polis</i> is the Greek for city.'),

('Plato against Aristotle &middot; which theory matches which philosopher',
 'Plato and Aristotle both use the word form. What is the difference?',
 [('Plato puts form in the object; Aristotle puts it in a realm outside ours.',
   'This is the right distinction with the names swapped, and it is the commonest way to lose this mark.'),
  ('Plato puts the Forms in a transcendental realm outside ours; Aristotle puts form in the thing itself, together with the goal it is growing toward.',
   'For Plato the ideal forms are all in a realm outside this one, and the things around us are copies. Aristotle keeps the form in the dog and the tree, and adds the end it is heading for. That is why he can be called the first biologist and Plato cannot.'),
  ('Plato means the shape of a physical object; Aristotle means the definition of a word.',
   'Neither of them means shape, and neither means a definition.'),
  ('They mean the same thing, and the disagreement is only about how we come to know it.',
   'The disagreement is about where the form is, which is a disagreement about what exists.')],
 2, 'One of the two could do biology. Which one, and why does that follow from where he puts form?'),

('Aristotle &middot; what form answers',
 "In the lecture, Aristotle's form and <i>telos</i> are offered as his answer to a question. Which question?",
 [('How can we be sure our senses are telling us the truth?',
   'That is the question put at the centre two thousand years later by Bacon and the <b>empiricists</b>, meaning the people who hold that knowledge starts in the senses.'),
  ('What makes a city just?',
   'That is the <i>Republic</i>.'),
  ('What causes movement, and where do things come from?',
   'This is the question the whole Greek picture is organised around, and the professor said so twice. <i>Physis</i> implies movement. Plato answers with the Forms in a realm outside ours. Aristotle answers with form in the thing and a goal it moves toward.'),
  ('Is technology part of nature or separate from it?',
   "That is Schadewaldt's question about <i>physis</i> and <i>techne</i>.")],
 3, '<i>Physis</i> was defined in the lecture as implying one particular thing. What was it?'),

('Aristotle &middot; what is critical to him',
 '<i>Telos</i> is the term she stressed as the one that is critical to Aristotle. What does it mean?',
 [('The end or goal of each living thing, meaning that everything has an intended purpose it is growing toward.',
   'The word literally means end. A dog, a tree and a person each have an end they are heading for, and knowing a thing means knowing that end. Remember it attached to Bacon, who hated it, and to Kuhn, who said the history of science cannot be explained by where it ended up.'),
  ('The material a thing is made out of.',
   'That is matter, which is the thing form is contrasted with.'),
  ('The distance between an appearance and the reality behind it.',
   "Closer to Plato's cave, and not a term from it."),
  ('The method of separating opinion from knowledge.',
   "That is dialectic, and it is Plato's.")],
 1, 'The word survives in English in <i>teleology</i>.'),

('The era question that is really about the person',
 'Which of these is true of Aristotle?',
 [('He was born in Athens to an aristocratic family and founded a school called the Academy.',
   'Every word of this is Plato. This is the trap, and she set it up in the lecture by giving both biographies together.'),
  ('He wrote twenty-six dialogues in which he never speaks in his own voice.',
   'Plato again.'),
  ('He lived roughly a century after Bacon and was influenced by the Scientific Revolution.',
   'Aristotle is 384 to 322 BCE. Bacon is 1561 to 1626 CE, so this has him about two thousand years late.'),
  ('He was born in Stagira, was never an Athenian citizen, studied with Plato, and tutored Alexander the Great.',
   '384 to 322 BCE, and the professor called him the first biologist. For her stated detail level you do not need the years, only that he is fourth century BCE and a generation after Plato.')],
 4, "Two of these four describe Plato's life."),

('Schadewaldt &middot; physis and techne',
 'What is the difference between <i>physis</i> and <i>techne</i>?',
 [('<i>Physis</i> is the study of nature and <i>techne</i> is the study of tools, so they are two branches of one subject.',
   'Neither word names a field of study. They name two kinds of thing in the world.'),
  ('<i>Physis</i> is nature, the creative origin that everything grows out of; <i>techne</i> is made by people, and is a combination of man and nature.',
   "<i>Physis</i> is the origin and centre of all activity, and it implies movement, which is why it answers the question about what causes things to move. <i>Techne</i> is not on its own a part of nature. Schadewaldt's whole complaint is that modern science pulled these two apart."),
  ('<i>Physis</i> is what can be measured and <i>techne</i> is what cannot.',
   'Reduction to the measurable is the modern move Schadewaldt is attacking, so this puts his own target into his vocabulary.'),
  ('<i>Physis</i> is the body and <i>techne</i> is the soul.',
   'No part of the lecture maps them onto body and soul.')],
 2, 'One of the two is where everything comes from. The other needs a person involved.'),

('What Wolfgang said',
 'Schadewaldt says the modern conception of nature has been "extraordinarily successful" and has cost us something. What is his complaint?',
 [('That science has produced weapons, so the problem is what the knowledge gets used for.',
   'His argument is about the conception of nature itself, before anyone applies it.'),
  ('That scientists no longer read the Greeks, so the tradition has been forgotten.',
   'A plausible thing for a classicist to say, and not what he says. The loss he names is in the concept itself.'),
  ('That nature has been reduced to what is calculable, which splits thought from extension, nature from spirit, and subject from object, and leaves an impoverishment that is hard to estimate.',
   'His word is dualism, meaning a split into two things that the Greeks held as one. The Greek <i>physis</i> held form and motion, law and life, causality and purpose together. Keeping only the calculable half works extremely well and drops the rest.'),
  ('That modern science makes claims it cannot prove, because induction never justifies a general law.',
   "A real problem, and a different one. Watch a thousand swans, see that every one is white, and conclude that all swans are white. The conclusion covers every swan there has ever been, and you looked at a thousand, so the thousand can never make it safe. Europeans believed exactly that until a Dutch expedition reached Western Australia in 1697 and found black ones. Reasoning upward from particular cases to a general law is called <b>induction</b>, and that gap is the problem of induction. It bites Bacon, whose method runs on it, and it bites the idea that knowledge is stacked like a brick wall on a bottom course that needs nothing under it, which is called <b>foundationalism</b>.")],
 3, 'He praises the results in the same sentence as the complaint, so look for what got left out.'),

('What Wolfgang said',
 'What does Schadewaldt propose as the way out of that dualism?',
 [('Stop using mathematics to describe nature.',
   'He calls the calculable approach extraordinarily successful. He wants to add to it.'),
  ('Give the humanities authority over what the sciences are allowed to study.',
   'Nothing in the lecture or the text proposes a change of authority.'),
  ('Replace <i>techne</i> with <i>episteme</i>, meaning theoretical knowledge of what never changes, so that knowing is theoretical again.',
   'The split he is attacking runs between nature and <i>techne</i>, so swapping one Greek word for another does not close it.'),
  ('Return man, as the observing subject, back into the act of inquiring into nature.',
   'The dualism puts the observer outside what is observed. His fix is to put the observer back inside it. This is the sentence to carry into week 5 and 6, because feminist epistemology makes the same move and gives it a different name.')],
 4, 'A dualism separates two things. Which two does he most want rejoined?'),

('Who Francis Bacon is',
 'How did the professor introduce Francis Bacon?',
 [('Early modern philosopher, 1561 to 1626, the father of empiricism, strongly influenced by the Scientific Revolution.',
   'Empiricism means the senses are the original source of knowledge. "Father of empiricism" is her phrase, and it is the one to have ready. His slogan is knowledge is power, and she stressed it means power over the physical world.'),
  ('The astronomer who found that the planets revolve around the sun.',
   "That is Galileo, 1564 to 1642, whom she used as her contrast to Bacon's complaint about Aristotle."),
  ('The philosopher who argued that a return to Greek values was necessary for society and education.',
   'That is Rousseau, 1712 to 1778.'),
  ('The historian who argued that Christian ideas about work shaped Western technology.',
   'That is Lynn White Jr.')],
 1, 'The word for his position comes from the Greek <i>empeiria</i>, experience.'),

('Which theory matches which philosopher',
 "In Bacon's simile, the ant, the spider and the bee stand for three ways of working. Who is the spider?",
 [('The alchemists, who only store things up and use them.',
   'That is the ant. Bacon calls them the empirics: they collect and never convert.'),
  ('The proper natural philosopher, who gathers material and then digests it.',
   'That is the bee, and it is the one Bacon wants you to be.'),
  ('The Aristotelians, who spin webs out of their own entrails.',
   "The dogmatists, in Bacon's word. The insult is precise: they produce elaborate systems out of themselves and take nothing in from the world. Ant collects and does not think, spider thinks and does not collect, bee does both."),
  ('The Greeks, who let ethics and politics dominate philosophy.',
   'A real Bacon complaint, and a separate one. He said that in Greece and Rome natural philosophy was left to perform the role of a servant.')],
 3, "Where does a spider's web physically come from?"),

('Bacon against Aristotle',
 "What exactly was Bacon's problem with the Aristotelian worldview?",
 [('That Aristotle relied on observation, and observation is unreliable.',
   'Backwards. Bacon is the one insisting on observation.'),
  ('<i>Telos</i>: a fundamental order that has to be understood, with the world revealing itself to the observer who waits for it.',
   'If everything already has a purpose built in, your job is to receive the order. Bacon wants you to go and get it, by experiment, which is why knowledge turns into power over the physical world. The contrast she used was Galileo, who found what the planets do by looking.'),
  ('That Aristotle placed the Forms in a realm outside this one.',
   "That is Plato's position, and this is the standard mix-up."),
  ('That Aristotle said nothing about method.',
   "Bacon's objection is to the method Aristotle has. An absence of method is a different charge.")],
 2, 'Bacon was also critical of the alchemists. What do they and the Aristotelians share, in his eyes?'),

('The Middle Ages &middot; Lynn White Jr.',
 "What is Lynn White's argument about technology in the Middle Ages?",
 [('Technology advanced once the Church lost its authority over learning.',
   'He argues the opposite: the religious worldview is the engine.'),
  ('New tools arrived from outside Europe and changed how Europeans thought about God.',
   'The causal arrow in his argument runs from the worldview to the technology.'),
  ('Technological change is driven by economic need, and religion follows along behind it.',
   'This is the position his argument is written against.'),
  ('Religious worldviews shape which technologies get developed, and the Judaeo-Christian picture made work itself a form of worship.',
   'His chain: God is a creator and an architect, man is made in his image and told to rule the world as a creative cooperator, and Christian history runs in one direction toward a goal, so there is no time to lose. Therefore work, including manual work, is worship. Around 1300 this produces Deism, God as the clockmaker who sets the world going.')],
 4, 'Which way does the causation run, from belief to tools or from tools to belief?'),

('Which theory matches which philosopher',
 "Which claim is Rousseau's?",
 [('A return to Greek values is necessary for society and education, and progress is only possible through education.',
   '1712 to 1778, French, shaped by the Enlightenment and the French Revolution. He idealises the Greek focus on science and art in education, and he says barbarous people are those who lack virtue, which the professor tied back to Plato, Socrates and Aristotle.'),
  ('The senses are the original source of knowledge.',
   'Bacon.'),
  ('Explanation passes through three historical stages before it becomes scientific.',
   'Comte, from the week 2 packet.'),
  ('Power and knowledge are one thing, aimed at controlling what we know.',
   'Foucault.')],
 1, 'He is the one in this week who looks backwards for his model.'),

('The circular jail',
 'Jeremy Bentham designed the panopticon. What is he most famous for?',
 [('The panopticon itself, which was built across Europe in the nineteenth century.',
   'The trap, and a real "single best answer" case. He is famous to us for the panopticon because of Foucault. The professor\'s own slide says he is most famous for utilitarianism, and his panopticon was never built in Britain.'),
  ('Utilitarianism. He also spent much of his life fighting for prison reform.',
   "Bentham held that the right action is whichever one produces the greatest happiness for the greatest number, and that doctrine is called <b>utilitarianism</b>. Her slide gave the two in that order. The prison reform is the link to the panopticon: he designed it as a humane replacement for what came before, which is exactly what makes Foucault's reading of it uncomfortable."),
  ('Founding the discipline of criminology.',
   'Not a claim made in the lecture.'),
  ('The theory that knowledge and power are the same thing.',
   "Foucault, who builds it on Bacon's knowledge is power.")],
 2, 'Ask what he was famous for while he was alive, before Foucault wrote about him in 1975.'),

('The circular jail',
 'A ring of cells, a tower at the centre, and wide windows in the tower. What makes the design work, according to Foucault?',
 [('One guard really can watch every cell at once, so no misbehaviour goes unseen.',
   'The defensible wrong answer, and the one most people pick. If the watching were genuinely constant the building would be an efficient prison and nothing more interesting.'),
  ('The prisoners can see each other, so they enforce the rules among themselves.',
   'The cells are divided from one another. The inmate is alone and seen, and not part of a group.'),
  ('The inmate is permanently visible and can never check whether the tower is occupied, so the watching has to be assumed and the inmate takes it over.',
   "Bentham's three words, which she listed on their own: visibility, unverifiability, and external power becoming non-corporeal. Non-corporeal means the power stops needing a body. Nobody has to be in the tower. The induced state of constant surveillance is produced by the uncertainty, which is why it costs almost nothing to run."),
  ('The threat of punishment is visible to everyone from outside the building.',
   'That is the older public spectacle of punishment that <i>Discipline and Punish</i> says the modern prison replaced.')],
 3, 'If the watching were genuinely constant, the building would be an ordinary efficient prison.'),

('The circular jail',
 'Foucault names three primary techniques of control in modern disciplinary society. Which three?',
 [('Confinement, torture and confession.',
   'Torture belongs to the older regime his book describes the end of.'),
  ('Surveillance, punishment and rehabilitation.',
   'Plausible, and none of these is his wording.'),
  ('Observation, classification and exclusion.',
   'All three ideas are in the text, and they are not the trio she listed.'),
  ('Hierarchical observation, normalizing judgment, and the examination.',
   'Learn them as a set of three, in her words. Hierarchical observation is watching arranged in ranks, and it produces power-knowledge, which she glossed from Foucault as "the development of force and the establishment of truth". Normalizing judgment measures you against a norm. The examination is where the two meet: it watches you and it records a verdict about you.')],
 4, 'All the words in the wrong options are real Foucault terms. Only one list is the trio she wrote down.'),

('Foucault &middot; History of Madness',
 'What does Foucault argue in <i>History of Madness</i>, 1961?',
 [('The claimed scientific neutrality of modern treatment of insanity covers for the control of challenges to conventional bourgeois morality.',
   'Her examples were homosexuality and hysteria, and both are worth remembering, because each was a medical diagnosis for behaviour that broke a social rule. What was presented as objective discovery, that madness is mental illness, came out of questionable social and ethical commitments.'),
  ('Madness does not exist and is invented by doctors.',
   'The overstated version people reach for. His claim is about what the category is doing, and not that nobody suffers.'),
  ('Treatment of the insane improved steadily once medicine became scientific.',
   'This is the progress story he is writing against.'),
  ('Mental illness is caused by the conditions inside asylums.',
   'His argument is about the classification. What causes the suffering is a separate question.')],
 1, 'Her two examples were homosexuality and hysteria. What do those two have in common?'),

('The era question',
 'Put these four in the order they worked, earliest first: Bentham, Copernicus, Rousseau, Bacon.',
 [('Bacon, Copernicus, Rousseau, Bentham',
   'Copernicus dies in 1543, eighteen years before Bacon is born. Bacon comes after.'),
  ('Copernicus, Bacon, Rousseau, Bentham',
   'Copernicus 1473 to 1543, Bacon 1561 to 1626, Rousseau 1712 to 1778, Bentham 1748 to 1832. Her detail standard is that you do not need the exact year, so carry centuries: Copernicus is late fifteenth into the sixteenth, Bacon straddles 1600, and Rousseau and Bentham overlap in the eighteenth.'),
  ('Copernicus, Rousseau, Bacon, Bentham',
   'Rousseau is born eighty-six years after Bacon dies.'),
  ('Bacon, Rousseau, Copernicus, Bentham',
   'Copernicus is the earliest of the four, and this puts him third.')],
 2, 'One of the four died before the other three were born.'),

('What is normal science',
 'What is normal science, for Kuhn?',
 [('Science done by ordinary researchers, as opposed to the work of the famous few.',
   'Normal describes the phase the field is in, and not the stature of the person doing it.'),
  ('Science that follows the proper method, as opposed to pseudoscience.',
   'Normal is not a compliment here, and Kuhn is not drawing a line around what counts as real science.'),
  ('Puzzle solving inside a shared paradigm, during the long stable stretches between revolutions.',
   'A <b>paradigm</b> is the whole shared kit a field works inside: its theories, its instruments, its values and its assumptions about what exists. "Normal science is puzzle solving" is her sentence. A puzzle has a known shape and an expected kind of answer, and the paradigm supplies both. Her examples of paradigms, taken from the chapter: Newton\'s mechanics, Lavoisier\'s chemistry, Mendel\'s genetics.'),
  ('The steady accumulation of facts that carries science closer to the truth over time.',
   'The tempting one, and it is the view Kuhn rejects. He denies that research makes steady progress. Normal science does accumulate, and the revolutions throw parts of it away.')],
 3, "Kuhn's word is puzzle, and he chose it over problem deliberately."),

('Incommensurability and the paradigm',
 'What is a paradigm?',
 [('A single theory that a field agrees is true.',
   'Too thin. A paradigm carries instruments and values and assumptions about what exists, and not a theory on its own.'),
  ('An experiment so decisive that it settles a dispute.',
   "A crucial experiment is the thing Kuhn's account makes hard to believe in."),
  ('A problem a field has failed to solve.',
   'A result a field cannot make fit, however hard it tries, is called an <b>anomaly</b>, and a pile of those is what eventually breaks a paradigm.'),
  ('A pattern for others to follow, working as a theoretical and methodological tool, carrying fixed theories, values, instruments and assumptions about what exists.',
   'Her phrase was "patterns for others to follow". Lavoisier\'s ideas about elements and the conservation of mass became the framework later chemists worked inside. Note the width of it, because that width is what makes incommensurability possible: if only a theory changed you could compare the two, and when the instruments and the values change with it there may be nothing left to compare them by.')],
 4, 'Ask how wide it is. If only a theory changed, you could still compare the two.'),

('Incommensurability and the paradigm',
 "What does incommensurability mean, and what were Kuhn's three reasons for it?",
 [('No common measure for comparing two paradigms. His three: the meanings of terms change, indoctrination, and historical context changes.',
   'The word means without a shared measure. Meanings change, so mass in Newton and mass in Einstein are two different things wearing one word. Indoctrination means scientists are trained into a paradigm, so they do not see from outside it. And historical context changes, so the question itself has moved. The critique she gave: many hold that the meanings problem can be overcome, and Kuhn softened his position and said communication stays difficult.'),
  ('Two theories cannot both be true. His three: contradiction, falsification and replacement.',
   "This is Popper's shape, and none of those three terms is Kuhn's."),
  ('Scientists in different fields cannot understand each other. His three: jargon, funding and institutional separation.',
   'Incommensurability runs between paradigms across time, and not between departments.'),
  ('Measurements made with different instruments cannot be compared. His three: calibration, precision and scale.',
   'A literal reading of the word, and she gave the counter-example herself: particle detectors stayed in use the same way while the theory changed around them.')],
 1, 'The word means without a shared measure. Her three reasons were about words, training and time.'),

("Why Kuhn's revolution is relevant",
 'Kuhn rejects Whig history. What is it, and what follows for how science gets told?',
 [("History written by the winners, so the losing side's arguments go unrecorded.",
   'Close in spirit and not her definition. The fault she named is about direction.'),
  ('History that builds the past into a series of steps toward present views, so events get explained by the fact that they led here. Kuhn says a sequence cannot be explained by what it turned into, because events have to follow their causes.',
   "This is the sentence she quoted from the chapter, and it is where Kuhn's revolution earns its place in a course about social values. Once the story stops running toward the present, the past stops being a set of mistakes on the way to us and becomes a set of other working systems. She also noted this is not the Aristotelian <i>telos</i>, where a thing genuinely moves toward an ideal form."),
  ('The view that science progresses by revolutions, which Kuhn replaced with steady accumulation.',
   'Backwards. Revolutions are his.'),
  ('The claim that political history and the history of science follow the same pattern.',
   'Not a position discussed in the lecture.')],
 2, 'Named after a political party, from a 1931 book. The fault is about the direction the story runs.'),

('The construction of kinds',
 'On the construction of kinds, what separates the nominalist from the realist?',
 [('The nominalist thinks classifications are useful; the realist thinks they are useless.',
   'Both sides think classification works. They disagree about why it works.'),
  ('The nominalist studies names and the realist studies things, so they are doing two different jobs.',
   'They are answering one question, about whether the categories were found or made.'),
  ('The nominalist says kinds are human impositions, so the objects of classification are mental and linguistic; the realist says kinds are real features of the world.',
   "Kevin flagged this one as examinable in the middle of his notes. The nominalist's hard part is that we agree on classifications very easily, which looks like evidence we are tracking something. Their answer is that shared training explains the agreement. Behind it is the position that our categories are human handiwork, which is called <b>constructivism</b>, set against realism: any given theory is not the only one that could have been established, so a theory's success is not by itself evidence that it is right."),
  ('The nominalist denies that the external world exists.',
   'The overstatement people reach for. The claim concerns our categories, and it leaves alone the question of whether there is anything out there.')],
 3, 'Both sides agree classification works. They disagree about why it works.'),

]
