# The single source for every definition in the course material.
#
# `short` is the one-line meaning. It is printed in a question's hint whenever the
# question uses that term, and it is also the opening of the cheat sheet entry, so
# the two can never drift apart. `extra` is the detail only the cheat sheet carries.
#
# Rule for `short`: it has to make sense read on its own, by someone who has looked
# up this one word and nothing else. No "that kit", no "as above", no back-references.

GROUPS = [
("general", "General words", [
 ("Ad hoc", "", "put together for the one case in hand, with no general rule behind it",
  "<b>Why it matters here.</b> Her conclusion about science was that it is an ad hoc system, disunified, and successful anyway. She attached that to Wittgenstein, whose example is games. What do all games have in common? Competition? Solitaire has none. Winning and losing? Ring-a-ring-a-roses has none. Skill? Snakes and ladders is pure luck. Two players? Solitaire again. Fun? Not professional sport. <b>No single feature is present in every game.</b> What there is instead is a web of overlaps: chess and poker share competition, poker and solitaire share cards, solitaire and patience share a single player. He called that a <b>family resemblance</b>, because relatives look alike with no one feature running through all of them. Her claim is that physics, taxonomy, epidemiology and geology are like that, and the whole thing works. So the course title gets an answer: there is no scientific method, singular, and that is survivable."),
 ("Contingent", "", "it could have been otherwise, and nothing made it necessary",
  "<b>Contingently real</b> means a thing is genuinely real and could still have been built differently. Week 4 says that of knowledge, methods, disciplinary boundaries and styles of work."),
 ("Epistemology", "", "a view about what counts as knowledge and how you are allowed to get it", ""),
 ("Metaphysics", "", "the study of what exists, and of what things fundamentally are",
  "The name is a filing accident. Compilers put Aristotle's book after his <i>Physics</i>."),
 ("Dualism", "", "a split of one thing into two",
  "Schadewaldt's complaint is that modern thought split nature from spirit, thought from extension, and subject from object, where the Greeks had held them together."),
]),

("greek", "The Greeks", [
 ("Homer", "eighth century BCE", "the earliest writer the course reaches back to",
  "The <i>Odyssey</i> relies on a cosmos with an order and a place for everything in it. That assumption is the ground everybody later argues on."),
 ("Heraclitus", "sixth century BCE", "nature is in harmony",
  "Sound thinking is man's greatest power, and his highest aptitude is being able to say what is and fashion creatively by hearkening to nature. Hearkening means listening, so the quotation assumes there is an order out there to listen to."),
 ("Aristotle", "384 to 322 BCE", "born in Stagira, never an Athenian citizen, studied under Plato, tutored Alexander the Great",
  "Called the first biologist. The non-citizenship is why he had to leave Athens at the end of his life."),
 ("Geocentrism", "Aristotle", "the earth at the centre of the universe, with everything else turning round it",
  "Nobody had to assume it. It falls out of the <i>telos</i> doctrine. Earth's natural place is the centre, which is why a dropped rock falls, and by the same reasoning the earth itself sits at the centre. The heavens are a different stuff that moves in perfect circles forever, because that is what that stuff is for. Copernicus and then Galileo broke it."),
 ("The Academy", "Plato", "his school in Athens, where the English word academy comes from",
  "Aristocratic women are known to have attended it."),
 ("<i>The School of Athens</i>", "Raphael, 1509 to 1511", "Plato points straight up, Aristotle holds his hand flat over the ground",
  "A fresco in the Vatican, and the single best mnemonic for the week 2 disagreement. <b>Plato's raised finger:</b> the Forms are in a realm outside this one, so the direction of inquiry is away from the visible world. He carries the <i>Timaeus</i>, his book about the cosmos. <b>Aristotle's flat palm:</b> form is in the thing, so the direction of inquiry is at the world you are standing in. He carries the <i>Ethics</i>, a book about how to live in this life."),
 ("The cave", "Plato", "prisoners chained facing a wall, taking the shadows on it for the real things",
  "<b>The journey.</b> Out of the <b>sensible</b> world, meaning what the senses reach, and up into the <b>intelligible</b> realm, meaning what only thought reaches. Plato calls the climb the journey of the soul. <b>Being freed is painful</b> and the prisoner has to be compelled. <b>The returner</b> is laughed at, and anyone who tries to unchain the others would be killed. <b>What it is for:</b> how we know what is true, how we check a fact, how we know where our information came from, and what methods of inquiry to use. Which makes it a text about method."),
 ("<span class='gk'>physis</span>", "Schadewaldt", "nature, meaning the source everything grows out of",
  "It carries movement inside it, which is why the Greeks used it to answer what makes things move."),
 ("<span class='gk'>techne</span>", "Schadewaldt", "skill at making or doing something",
  "A person has to be involved, so it is never a part of nature on its own."),
 ("<span class='gk'>episteme</span>", "Schadewaldt", "knowledge of what never changes",
  "Ranked above <span class='gk'>techne</span>, which works on things still in the middle of becoming."),
 ("<span class='gk'>empeiria</span>", "Schadewaldt", "plain experience: you can do the thing and cannot say why it works", ""),
 ("<span class='gk'>atechnia</span>", "Schadewaldt", "making something confidently out of a false idea of how it works",
  "His word for a blunder. It can be elaborate and productive and still be one."),
 ("<span class='gk'>telos</span>", "Aristotle", "the end a thing is growing toward",
  "An acorn is heading for oak. To know a thing is to know its end. The root of the English <i>teleology</i>."),
 ("Form", "Plato and Aristotle", "what makes a thing the kind of thing it is",
  "<b>Plato</b> puts the Forms in a realm outside this one and makes everything here a copy. <b>Aristotle</b> puts form inside the thing, together with its end. That is why Aristotle could do biology and Plato could not."),
 ("Dialectic", "Plato", "question and answer until opinion has been sorted out from knowledge", ""),
 ("Kalliopolis", "Plato", "his beautiful city, run by philosopher kings, where the right education is what holds it together",
  "She wrote on her own slide that Foucault's perfectly governed city should make you think of it."),
 ("Philosopher kings", "Plato", "the rulers of his ideal city, described as awake while everyone else dreams",
  "Their education needs geometry and astronomy, because mathematics is his route to what you cannot touch."),
]),

("method", "Method and knowledge", [
 ("Empiricism", "Bacon", "the view that the senses are where knowledge starts",
  "From the Greek <span class='gk'>empeiria</span>, experience. Its opposite is the view that reason alone gets you there, which is Plato."),
 ("Induction", "", "reasoning up from the cases you have seen to a law covering all of them",
  "A thousand swans, every one white, so all swans are white. The law covers every swan there is and you looked at a thousand, so the cases never make it safe. Europeans held that one until 1697, when a Dutch expedition found black swans in Western Australia."),
 ("Foundationalism", "", "every claim rests on a claim below it, down to a bottom layer that needs nothing under it",
  "Why will the kettle boil at 100? Because water does. Why believe that? Because every measurement came out that way. There the chain is meant to stop. The problem is that the bottom layer is laid by induction. The tracing runs down through reasons. Tracing back through time is a separate idea, called <b>Whig history</b>."),
 ("Knowledge is power", "Bacon", "know how a thing works and you can make it do what you want",
  "He means power over the physical world, and he means it as a promise. Foucault later keeps the equation and turns it into an accusation."),
 ("Ant, spider, bee", "Bacon", "three ways of working, two of them wrong",
  "The alchemists are ants: they pile material up and do nothing with it. The Aristotelians are spiders: they spin systems out of themselves with no material coming in. The proper natural philosopher is a bee, who gathers and then digests. <i>Novum Organum</i> I.95."),
 ("Lynn White Jr.", "", "religious worldviews decide which technologies get built",
  "His chain, in order. God is a creator and an architect. Man is made in his image and told to rule the world as a creative cooperator. Judaeo-Christian history runs in one direction toward a goal, where most religions had time going round in a circle. So there is no time to lose, and manual work becomes an essential and pressing form of worship. The position he is arguing against is that economic need drives technology and religion follows along behind."),
 ("Deism", "Lynn White", "God as a clockmaker who set the world going and stepped back",
  "Developing around 1300. Once the world is a mechanism, taking it apart to see how it runs becomes a pious act."),
 ("Comte's three states", "", "explanation passes through three stages over history: theological, then metaphysical, then positive",
  "Gods explain things, then abstract essences and forces explain them, then only what can be observed and measured counts. The third stage is where the word positivism comes from. Note that this is a progress story, which puts Comte on the opposite side from Kuhn."),
 ("The Vienna Circle", "1920s and 1930s", "philosophers and scientists holding that a statement means something only if it can be checked against experience",
  "Logical positivism, with Moritz Schlick at the centre. The hardest and most organised version of the doctrine Kuhn's book breaks with."),
 ("Descartes", "", "split the world into thinking substance and extended substance",
  "<b>Extension</b> means taking up space. Mind on one side, everything physical on the other. This is the dualism Schadewaldt wants undone, because it puts the observer outside what is observed."),
 ("Galileo", "1564 to 1642", "found by looking that the planets revolve around the sun",
  "The counter-example to Aristotle's patient observer waiting for the world to reveal its purposes. He went and got the answer."),
 ("Positivism", "", "the doctrine that real knowledge comes only from what you can observe and measure",
  "Three demands on method follow. <b>Non-contextual</b>: the result cannot depend on who ran it, or where, or when. <b>Standardised</b>: anyone following the same procedure gets the same result. <b>Analytic</b>: isolate one variable and hold the rest still. Kuhn attacks the first, since a paradigm is a context. Positive here has nothing to do with good."),
 ("Realism", "", "there is one way the world is, and we can find it out and describe it accurately",
  "Truths depend mostly on the natural world and only slightly on the people stating them."),
 ("Instrumentalism", "", "a theory is a tool that works, with no claim attached about what is really there",
  "The opposite of realism."),
]),

("kuhn", "Kuhn", [
 ("Normal science", "", "solving puzzles where the final picture is already agreed, and every piece you place leads toward it",
  "A puzzle has a guaranteed answer, so failing one counts against you. The picture stays where it is. That asymmetry is what lets a field carry on through years of bad results."),
 ("Paradigm", "", "the shared picture a field works from, with the instruments, standards and assumptions that come with it",
  "Her examples: Newton's mechanics, Lavoisier's chemistry, Mendel's genetics. Note how wide it is, because that width is what makes incommensurability possible."),
 ("Disciplinary matrix", "", "Kuhn's later and more careful word for a paradigm", ""),
 ("Anomaly", "", "a result the field cannot make fit, however hard it tries",
  "They pile up, and a pile of them is what eventually breaks a paradigm."),
 ("Revolution", "", "the shared picture gets replaced, and the result that would not fit is finally explained",
  "Not progress, because it builds and destroys at the same time, so there is no single direction left to measure."),
 ("Incommensurability", "", "no shared unit for measuring two paradigms against each other",
  "From geometry: a square's side and its diagonal have no common unit that fits both exactly.<br><br><b>The case to carry.</b> In Newton, mass is a fixed property of an object, the same whatever the object is doing. In Einstein it changes with velocity. Same word, two different things, so \"mass is conserved\" is true in one theory and false in the other.<br><br><b>His three reasons:</b> the meanings of terms change, indoctrination, and historical context changes. <b>Her counter-example:</b> particle detectors stayed in use unchanged across a theory change, so something survived that both sides trust."),
 ("Whig history", "", "telling the past as a line of steps leading up to us",
  "Kuhn's objection is logical: events have to follow their causes, so a sequence cannot be explained by the fact that it ended up here."),
 ("Copernicus", "1473 to 1543", "he put the sun at the centre and set the earth moving",
  "Her framing, and she called it the important one: he needed the sun at the centre for circular motion to work. He was keeping an old Greek commitment to perfect circles, with no new data behind the move."),
]),

("foucault", "Foucault", [
 ("Panopticon", "Bentham", "a ring of cells round a central tower, where the inmate is always visible and can never check whether anyone is watching",
  "Two windows per cell, so light crosses it and the occupant shows as a silhouette. The architecture does the watching, which is why one person can replace many."),
 ("Bentham's three words", "", "visibility, unverifiability, and external power becoming non-corporeal",
  "Non-corporeal means the power stops needing a body in the tower. Nobody has to be up there, so it costs almost nothing to run."),
 ("Utilitarianism", "Bentham", "the right action is whichever produces the greatest happiness for the greatest number",
  "What he was actually famous for in his lifetime, ahead of the panopticon. He also spent much of his life on prison reform."),
 ("Three techniques of control", "", "hierarchical observation, normalizing judgment, and the examination",
  "Watch, rank, record. Hierarchical observation is watching arranged in ranks. Normalizing judgment measures you against a norm. The examination is where the two meet: it watches you and writes a verdict about you in one act."),
 ("Power-knowledge", "", "knowing someone and controlling them turn out to be a single act",
  "His gloss: the development of force and the establishment of truth. A file written about a prisoner becomes the truth about him and decides whether he goes home. Built on Bacon's knowledge is power, with the verdict reversed."),
 ("Normalization", "", "a norm gets set and everyone is measured against it, so people sort into normal and abnormal",
  "She called it the goal of disciplinary power. Her examples are all places nobody is being punished: standardized education, medical practice, industrial production."),
 ("Docile bodies", "", "bodies made useful and easier to control by discipline",
  "Prisoners, soldiers, workers, schoolchildren. The body is broken into segments, analysed in detail, and recomposed for maximum effect."),
 ("Genealogy", "", "studying how a practice came to be, without assuming it was an improvement",
  "The method of <i>Discipline and Punish</i>, 1975. His puzzle: punishment really did get gentler, so what is the gentler method doing that the old one could not?"),
 ("The plague town", "", "how <i>Panopticism</i> opens: the plague is met with Order",
  "Sorting the disease, separating bodies, sorting evil, which increases fear and death. Its political dream is strict division and regulation reaching into the smallest details of daily life."),
 ("<i>History of Madness</i>", "1961", "psychiatry's claimed neutrality covers for controlling people who break social rules",
  "Her examples: homosexuality and hysteria. What was presented as objective discovery came out of questionable social and ethical commitments."),
]),

("week4", "Week 4", [
 ("Stratification", "", "a field layering into a small advantaged group and everyone else",
  "Ten per cent of authors produce half of all papers. Eighty per cent of citations go to twenty per cent of papers."),
 ("Cumulative advantage", "", "success breeds success, so an early lead compounds into a large one",
  "A good first post means a bigger lab, more results, a stronger grant, a bigger lab again. Nobody does anything unfair and the gap widens anyway."),
 ("Meritocracy", "", "a system where who gets ahead tracks how good they are",
  "Her conclusion was that science looks much more like a boys' club than one of these."),
 ("Zuckerman 1977", "", "34 of the 55 US Nobel laureates in 1963 had worked with a previous winner",
  "Those who had won at an average age of 44, against 53 for the others."),
 ("Rossiter", "", "a field's status drops as women enter it and rises as men do",
  "Women were pushed into the invisible sciences, such as home economics and nutritional science. In 1982 men perceived their own work as less masculine because women were present."),
 ("Wenneras and Wold 2001", "", "a woman needed about three extra <i>Nature</i> papers to be scored as competent as a man",
  "Or twenty extra in a good specialist journal. At the Swedish Medical Research Council, in peer review, which is the mechanism science uses to be fair."),
 ("Fox 1983", "", "the portrait of a productive scientist",
  "Driven, strong ego, acts autonomously, plays with ideas, tolerates ambiguity, at home with abstractions, detached from non-scientific social relations, reserves mornings for writing, works on routinised problems, relatively young, prestigious graduate school, prestigious mentor, prestigious employer, free to choose problems, a history of success. Half of it is a personality and half of it is a situation."),
 ("Hermanowicz 2006", "", "the same thing as behavioural categories, in order of importance",
  "Persistent, smart, civil, creative, entrepreneurial, aggressive, tasteful, confident, adaptable. Persistence outranks intelligence and civility comes third."),
 ("Cole and Cole", "", "funding goes to the most influential, and to institutions trusted largely for having been around a long time",
  "So funding opportunities feed stratification."),
 ("Cole and Singer 1991", "", "small irritants compound",
  "Each difference looks trivial and gets shrugged off. Where competition is strong and advantage accumulates, trivial differences at the start produce large gaps later."),
 ("Barbercheck 2001", "", "the words in advertisements in the journal <i>Science</i>",
  "Simple and easy go with pictures of women. Fast, reliable and accurate go with pictures of men. Men are also more likely to be shown as heroes, as nonconformists, and at play."),
 ("Etzkowitz 2000", "", "exclusion from the informal networks where technical knowledge moves",
  "A female doctoral student: her colleagues went to parties with her, and it never crossed their minds to ask her which drying agent to use. Nobody refused her anything."),
 ("The pipeline", "", "a pipe with leaks at every joint along its span",
  "A high-pressure surge of young women at the source and a trickle at the spigot. No single point of failure, so no single fix. Getting in, staying in, getting on."),
 ("Gilligan and Keller", "1982 and 1985", "women tend to think in more concrete terms, so are better served by problem-centred learning",
  "A live proposal about learning styles, from inside feminism as well as outside it. Keep it apart from the maths gene claim, which is rejected."),
 ("The maths gene", "Benbow and Stanley, and Summers in 2005", "the claim that boys have an inborn advantage in mathematics",
  "Rejected on two grounds. Genes only ever act in environments, so a claim about genes alone is a claim about nothing. And boys' and girls' scores have been converging, while genes do not change in thirty years."),
 ("Social construction", "", "facts, theories and technologies get built by people, and are not simply found lying there",
  "Truth, rationality and the material world have limited value without interpretation or rhetorical work."),
 ("Constructivism", "Hacking 1999", "our categories are human handiwork",
  "Any given theory is not the only one that could have been established, so a theory's success is not by itself evidence for it."),
 ("How a thing gets to be real", "", "enough people act as though it exists, so it cannot be wished away",
  "Her example is politeness: no law requires it, no building houses it, and it constrains everybody. The test offered for reality is causal power. Gender is real because treating people as gendered produces gendered people."),
 ("Nominalist and realist about kinds", "", "are our categories imposed by us, or found in the world?",
  "<b>Nominalist:</b> kinds are human impositions, so the objects of classification are mental and linguistic. <b>Realist:</b> kinds are real features of the world. Her test case was ADHD."),
 ("Knorr Cetina", "", "nature is not to be found in the laboratory",
  "To an outside observer it is a site of action from which nature is as much as possible excluded: a space of prepared materials, intentionally shaped."),
 ("Heterogeneous engineering", "Law 1987", "building the device and the world it can work in at the same time",
  "Enrolling materials, skills, knowledge, capital and people who may not fit together. No one piece of the network decides the shape of the whole."),
 ("Co-production", "", "scientific knowledge and social arrangements make each other",
  "Researchers need funding to study climate change, and the science then justifies the policy. ADHD can be framed as a disorder or as extreme procrastination."),
]),
]
