# Short definitions, pulled from the cheat sheet glossary. The builder scans every
# question stem for these and prints the matching ones inside that question's hint,
# so a term never appears in a question without its meaning one click away.
GLOSS = {
 "normal science": "the long stable stretch when a field works inside one shared paradigm and solves puzzles",
 "paradigm": "the whole shared kit a field works inside: its theories, instruments, values and assumptions about what exists",
 "disciplinary matrix": "Kuhn's later and more careful word for a paradigm",
 "incommensurab": "no shared unit for comparing two paradigms, so neither can be measured against the other",
 "anomal": "a result a field cannot make fit however hard it tries",
 "whig history": "history that builds the past into a series of steps leading to us",
 "foundationalis": "the idea that every claim rests on a lower claim, down to a bottom layer that needs no reason under it",
 "inductive": "reasoning upward from particular cases to a general law, the way a thousand white swans suggest that all swans are white",
 "induction": "reasoning upward from particular cases to a general law, the way a thousand white swans suggest that all swans are white",
 "positivis": "the doctrine that real knowledge comes only from what you can observe and measure",
 "empiricis": "the view that the senses are the original source of knowledge",
 "telos": "the end or goal a thing is growing toward, in Aristotle",
 "physis": "nature, the creative origin everything grows out of",
 "techne": "skill at making or doing something, which people produce",
 "episteme": "theoretical knowledge, of what never changes",
 "empeiria": "plain experience, know-how with no account behind it",
 "atechnia": "productive knowledge built on a false idea of the thing, held confidently",
 "dialectic": "Plato's method of inquiry, separating opinion from knowledge",
 "metaphysic": "the study of what exists and what things fundamentally are",
 "genealogical": "a study of how a practice came to be, without assuming it was an improvement",
 "normaliz": "setting a norm and measuring everyone against it, so people sort into normal and abnormal",
 "power-knowledge": "Foucault's claim that knowing someone and controlling them are one act",
 "hierarchical observation": "watching arranged in ranks, each level watched by the one above",
 "docile": "made useful and easier to control by discipline",
 "utilitarian": "the doctrine that the right action is whichever produces the greatest happiness for the greatest number",
 "panopticon": "Bentham's ring of cells round a central tower, where the inmate is always visible and can never check whether anyone is watching",
 "kalliopolis": "Plato's beautiful city, ruled by philosopher kings",
 "ad hoc": "put together for the particular case in hand, with no general rule behind it",
 "contingent": "it could have been otherwise, and nothing made it necessary",
 "nominalis": "the view that kinds are human impositions, so the objects of classification are mental and linguistic",
 "constructivis": "the view that our categories are human handiwork",
 "co-produc": "scientific knowledge and social arrangements making each other",
 "heterogeneous": "mixing material things and social things in one network",
 "stratificat": "the layering of a field into a small advantaged group and everyone else",
 "cumulative advantage": "success breeding success, so early advantage compounds",
 "meritocra": "a system where who gets ahead tracks how good they are",
 "epistemolog": "a view about what counts as knowledge and how you may get it",
 "instrumentalis": "the view that a theory is a useful tool and never a claim about what is really there",
 "deism": "God as a clockmaker who set the world going and stepped back",
 "dualis": "a split of one thing into two",
 "propensity": "an inborn tendency",
 "ideological": "stating a political position while dressed as a finding",
}
